import type { Language } from "../types";

/* SPANISH · A Mexican-American family. Six chapters, from Abuela's ofrenda to a video call with the pueblo. */

const meta: Language = {
  id: "spanish",
  lang: "es-MX",
  speech: "es",
  language: "Spanish",
  native: "Español",
  family: "A Mexican-American family",
  variety: "Spanish · Mexican",
  script: "latin",
  romanize: false,
  line: "A Mexican-American family, from Día de Muertos to Las Posadas. One Spanish-speaking world of many.",
  journeys: ["Mexican family experiences", "Mexican-American life across two homes", "Latin American traditions", "Other Spanish-speaking family stories"],
  a: "#c8503f",
  b: "#1f6b4f",
  rank: 4,
  speakers: {
    abuela: { name: "Abuela", glyph: "A", tone: "elder" },
    mama: { name: "Mamá", glyph: "M", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    { id: "agua", native: "agua", roman: "agua", english: "water", group: "food", where: "the pitcher in the kitchen", ch: 1 },
    { id: "pan", native: "pan", roman: "pan", english: "bread", group: "food", where: "the basket of pan dulce", ch: 1 },
    { id: "sal", native: "sal", roman: "sal", english: "salt", group: "food", where: "the kitchen counter", ch: 1 },
    { id: "vela", native: "vela", roman: "vela", english: "candle", group: "home", where: "a box in the kitchen", ch: 1 },
    { id: "flor", native: "flor", roman: "flor", english: "flower", group: "home", where: "a pot on the patio", ch: 1 },
    { id: "casa", native: "casa", roman: "casa", english: "home · house", group: "home", where: "the living-room window", ch: 1 },
    { id: "foto", native: "foto", roman: "foto", english: "photo", group: "home", where: "the ofrenda", ch: 1 },
    { id: "familia", native: "familia", roman: "familia", english: "family", group: "family", where: "the photos on the wall", ch: 1 },
    { id: "mama", native: "mamá", roman: "mamá", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "papa", native: "papá", roman: "papá", english: "dad", group: "family", where: "his guitar", ch: 1 },
    { id: "abuela", native: "abuela", roman: "abuela", english: "grandmother", group: "family", where: "the armchair", ch: 1 },
    { id: "bisabuelo", native: "bisabuelo", roman: "bisabuelo", english: "great-grandfather", group: "family", where: "the ofrenda", ch: 1 },
    { id: "pueblo", native: "pueblo", roman: "pueblo", english: "hometown · village", group: "home", where: "Abuela's town in Michoacán", ch: 2 },
    { id: "tianguis", native: "tianguis", roman: "tianguis", english: "open-air market", group: "home", where: "Sunday in the plaza", ch: 2 },
    { id: "naranja", native: "naranja", roman: "naranja", english: "orange", group: "food", where: "Doña Chela's fruit stall", ch: 2 },
    { id: "aguacate", native: "aguacate", roman: "aguacate", english: "avocado", group: "food", where: "Doña Chela's fruit stall", ch: 2 },
    { id: "jitomate", native: "jitomate", roman: "jitomate", english: "tomato", group: "food", where: "Doña Chela's fruit stall", ch: 2 },
    { id: "limon", native: "limón", roman: "limón", english: "lime", group: "food", where: "Doña Chela's fruit stall", ch: 2 },
    { id: "peso", native: "peso", roman: "peso", english: "peso", group: "home", where: "paying at the tianguis", ch: 2 },
    { id: "dos", native: "dos", roman: "dos", english: "two", group: "home", where: "paying at the tianguis", ch: 2 },
    { id: "tres", native: "tres", roman: "tres", english: "three", group: "home", where: "paying at the tianguis", ch: 2 },
    { id: "cinco", native: "cinco", roman: "cinco", english: "five", group: "home", where: "paying at the tianguis", ch: 2 },
    { id: "diez", native: "diez", roman: "diez", english: "ten", group: "home", where: "paying at the tianguis", ch: 2 },
    { id: "cuanto", native: "¿cuánto?", roman: "¿cuánto?", english: "how much?", group: "home", where: "Abuela's bargaining", ch: 2 },
    { id: "caro", native: "caro", roman: "caro", english: "expensive", group: "home", where: "the pottery stall", ch: 2 },
    { id: "gracias", native: "gracias", roman: "gracias", english: "thank you", group: "home", where: "Don Beto's stall", ch: 2 },
    { id: "tia", native: "tía", roman: "tía", english: "aunt", group: "family", where: "the kitchen table", ch: 3 },
    { id: "primo", native: "primo", roman: "primo", english: "cousin (boy)", group: "family", where: "the courtyard", ch: 3 },
    { id: "tamal", native: "tamal", roman: "tamal", english: "tamale", group: "food", where: "the kitchen table", ch: 3 },
    { id: "masa", native: "masa", roman: "masa", english: "corn dough", group: "food", where: "the big bowl", ch: 3 },
    { id: "hoja", native: "hoja", roman: "hoja", english: "corn husk · leaf", group: "food", where: "the tub in the courtyard", ch: 3 },
    { id: "maiz", native: "maíz", roman: "maíz", english: "corn", group: "food", where: "the sacks by the door", ch: 3 },
    { id: "salsa", native: "salsa", roman: "salsa", english: "salsa · sauce", group: "food", where: "the molcajete", ch: 3 },
    { id: "cuchara", native: "cuchara", roman: "cuchara", english: "spoon", group: "home", where: "the kitchen table", ch: 3 },
    { id: "olla", native: "olla", roman: "olla", english: "cooking pot", group: "home", where: "on the fire", ch: 3 },
    { id: "mesa", native: "mesa", roman: "mesa", english: "table", group: "home", where: "the kitchen", ch: 3 },
    { id: "rico", native: "rico", roman: "rico", english: "delicious", group: "food", where: "the first tamal", ch: 3 },
    { id: "posada", native: "posada", roman: "posada", english: "shelter · an inn", group: "home", where: "the procession", ch: 4 },
    { id: "noche", native: "noche", roman: "noche", english: "night", group: "home", where: "the street at dusk", ch: 4 },
    { id: "calle", native: "calle", roman: "calle", english: "street", group: "home", where: "the procession", ch: 4 },
    { id: "vecino", native: "vecino", roman: "vecino", english: "neighbour", group: "family", where: "the procession", ch: 4 },
    { id: "puerta", native: "puerta", roman: "puerta", english: "door", group: "home", where: "every house on the street", ch: 4 },
    { id: "cantar", native: "cantar", roman: "cantar", english: "to sing", group: "home", where: "the procession", ch: 4 },
    { id: "pinata", native: "piñata", roman: "piñata", english: "piñata", group: "home", where: "Doña Chela's courtyard", ch: 4 },
    { id: "estrella", native: "estrella", roman: "estrella", english: "star", group: "home", where: "the piñata", ch: 4 },
    { id: "dulces", native: "dulces", roman: "dulces", english: "sweets", group: "food", where: "inside the piñata", ch: 4 },
    { id: "ponche", native: "ponche", roman: "ponche", english: "warm fruit punch", group: "food", where: "the clay pot on the fire", ch: 4 },
    { id: "cuatro", native: "cuatro", roman: "cuatro", english: "four", group: "home", where: "sharing the sweets", ch: 4 },
    { id: "seis", native: "seis", roman: "seis", english: "six", group: "home", where: "sharing the sweets", ch: 4 },
    { id: "luz", native: "luz", roman: "luz", english: "light · the power", group: "home", where: "the night the power went out", ch: 5 },
    { id: "oscuro", native: "oscuro", roman: "oscuro", english: "dark", group: "home", where: "the night the power went out", ch: 5 },
    { id: "cerillos", native: "cerillos", roman: "cerillos", english: "matches", group: "home", where: "the kitchen drawer", ch: 5 },
    { id: "linterna", native: "linterna", roman: "linterna", english: "flashlight", group: "home", where: "the kitchen drawer", ch: 5 },
    { id: "sombra", native: "sombra", roman: "sombra", english: "shadow", group: "home", where: "the wall by the candle", ch: 5 },
    { id: "cuento", native: "cuento", roman: "cuento", english: "story · tale", group: "home", where: "Abuela's story", ch: 5 },
    { id: "luna", native: "luna", roman: "luna", english: "moon", group: "home", where: "over the courtyard", ch: 5 },
    { id: "conejo", native: "conejo", roman: "conejo", english: "rabbit", group: "home", where: "Abuela's story", ch: 5 },
    { id: "hambre", native: "hambre", roman: "hambre", english: "hunger", group: "home", where: "Abuela's story", ch: 5 },
    { id: "cielo", native: "cielo", roman: "cielo", english: "sky", group: "home", where: "Abuela's story", ch: 5 },
    { id: "recuerdo", native: "recuerdo", roman: "recuerdo", english: "keepsake · memory", group: "home", where: "your suitcase", ch: 6 },
    { id: "maleta", native: "maleta", roman: "maleta", english: "suitcase", group: "home", where: "your room", ch: 6 },
    { id: "tio", native: "tío", roman: "tío", english: "uncle", group: "family", where: "the video call", ch: 6 },
    { id: "prima", native: "prima", roman: "prima", english: "cousin (girl)", group: "family", where: "the video call", ch: 6 },
    { id: "abrazo", native: "abrazo", roman: "abrazo", english: "hug", group: "family", where: "the video call", ch: 6 },
    { id: "extranar", native: "te extraño", roman: "te extraño", english: "I miss you", group: "family", where: "the video call", ch: 6 },
    { id: "pronto", native: "pronto", roman: "pronto", english: "soon", group: "home", where: "saying goodbye", ch: 6 },
    { id: "hasta", native: "hasta pronto", roman: "hasta pronto", english: "see you soon", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    rebozo: { title: "Abuela's rebozo", native: "rebozo", note: "A woven shawl from Michoacán. She wears it for anything that matters and folds it over the sofa in between." },
    cempasuchil: { title: "Cempasúchil", native: "cempasúchil", note: "Mexican marigolds. The name comes from Nahuatl, the language of the Aztecs. Their colour and scent are said to guide the dead home." },
    molcajete: { title: "Molcajete", native: "molcajete", note: "A three-legged bowl carved from volcanic stone, for grinding salsa. Older than Mamá." },
    ofrenda: { title: "The ofrenda", native: "ofrenda", note: "An altar of remembrance for Día de Muertos: photos, candles, flowers, water, salt, and the food the person loved." },
    papel: { title: "Papel picado", native: "papel picado", note: "Tissue paper cut into lace-like banners, strung over the ofrenda." },
    tianguis: { title: "The tianguis", native: "tianguis", note: "From the Nahuatl tianquiztli. Open-air markets have set up in Mexican plazas on the same weekday since long before the Spanish arrived." },
    pilon: { title: "El pilón", native: "el pilón", note: "The little extra a vendor drops in the bag for a regular — one more lime, a sweet for the kid. Abuela always gets the pilón." },
    aguas: { title: "Aguas frescas", native: "aguas frescas", note: "Jamaica, horchata, tamarindo — ladled from glass barrels into plastic bags with a straw." },
    barro: { title: "Barro", native: "barro", note: "Clay pots from Michoacán. Beans taste better in them, Abuela says, and nobody argues." },
    tamalada: { title: "The tamalada", native: "tamalada", note: "A tamale-making party. The more hands at the table, the faster it goes — and the more stories get told." },
    champurrado: { title: "Champurrado", native: "champurrado", note: "Thick hot chocolate made with masa. What you drink at a tamalada while you wait for the first batch." },
    comal: { title: "The comal", native: "comal", note: "A flat griddle over the fire, for tortillas. Abuela's is black from forty years of use." },
    posadas: { title: "Las Posadas", native: "las posadas", note: "Nine nights, December 16th to 24th. Neighbours walk door to door singing, re-enacting Mary and Joseph's search for a place to stay." },
    pinata: { title: "The star piñata", native: "piñata", note: "The traditional piñata has seven points. Breaking it is breaking the seven deadly sins — and then there are sweets." },
    ponche: { title: "Ponche navideño", native: "ponche", note: "Guava, tejocote, sugarcane, cinnamon and piloncillo, simmered for hours in a clay pot." },
    luna: { title: "El conejo en la luna", native: "el conejo en la luna", note: "Look at the full moon's dark patches: in Mexico, people see a rabbit. The story goes back to the Aztecs." },
    sombras: { title: "Shadow puppets", native: "sombras", note: "When the power goes out, the wall becomes a stage. Every abuela knows how to make a rabbit." },
  },
  memoryNotes: {
    kitchen: { title: "Helped Mamá in the kitchen", note: "Bread, water, candles, salt — passed by ear, in Spanish." },
    ofrenda: { title: "Built the ofrenda", note: "His photo at the top. Candles, marigolds and pan de muerto below." },
    story: { title: "Bisabuelo Ramón's story", note: "From a pueblo in Michoacán to a panadería on your street." },
    remember: { title: "“Es mi bisabuelo.”", note: "Abuela asked who he was. You told her — in Spanish." },
    pesos: { title: "Paid in pesos", note: "Dos, tres, cinco, diez — counted out at Doña Chela's stall." },
    haggle: { title: "Watched Abuela bargain", note: "Three hundred pesos became two hundred and fifty." },
    gracias: { title: "“Nada más, gracias.”", note: "Don Beto asked if you needed anything else. You told him — in Spanish." },
    hands: { title: "Passed things to Tía Lupe", note: "Masa, hojas, salsa, cuchara — by ear." },
    tamales: { title: "Made tamales", note: "Soak, spread, fill, fold, into the pot." },
    rico: { title: "“¡Están muy ricos!”", note: "The first tamal of the day. You told Tía Lupe it was delicious." },
    posada: { title: "Walked the posada", note: "Candle in hand, door to door, until someone let you in." },
    sweets: { title: "Shared out the sweets", note: "Tres, cuatro, cinco, seis — nobody got fewer than anyone else." },
    encanto: { title: "“¡Me encantó!”", note: "Abuela asked if you liked your first posada." },
    dark: { title: "Found the matches in the dark", note: "Cerillos, velas, linterna — by feel." },
    moonstory: { title: "The rabbit in the moon", note: "Heard by candlelight, with the power out." },
    conejo: { title: "“Sí, veo el conejo.”", note: "You looked up at the full moon — and saw him." },
    keepsakes: { title: "Unpacked the pueblo", note: "A clay pot, a bag of dulces, a piñata point." },
    call: { title: "Named everyone on the call", note: "Tío Chuy, Tía Lupe, Mateo, Lupita." },
    retold: { title: "Told your trip in Spanish", note: "Tianguis, tamales, posada, luna — in order." },
    hastapronto: { title: "“¡Hasta pronto!”", note: "Not goodbye. See you soon." },
  },
  chapters: [
    {
      n: 1,
      name: "La Ofrenda",
      native: "La Ofrenda",
      subtitle: "Día de Muertos at home",
      synopsis:
        "October 31st in a Mexican-American home. Across the street, kids are trick-or-treating; in the living room, Abuela is getting the ofrenda ready for your great-grandfather. Pick the cempasúchil, help Mamá in the kitchen, build the ofrenda — and hear the story of the man in the photo.",
      homeLines: {
        start: "It's October 31st. Abuela needs help building the ofrenda.",
        going: "The ofrenda is still waiting. Abuela is in her armchair.",
        done: "The ofrenda is built and Bisabuelo Ramón has his story back. Next: El Mercado.",
      },
    },
    {
      n: 2,
      name: "El Mercado",
      native: "El Mercado",
      subtitle: "Sunday at the tianguis",
      synopsis: "Abuela takes you to the Sunday tianguis in her town in Michoacán. Ask for what's on her list, count out pesos, and find out why every stall-keeper knows her name.",
      homeLines: { start: "Abuela's ready for the tianguis. Bring the bag.", going: "The tianguis is still busy, and Abuela still has a list.", done: "The bags are full and the pesos counted. Next: the tamalada." },
    },
    {
      n: 3,
      name: "La Tamalada",
      native: "La Tamalada",
      subtitle: "Tamales take all day",
      synopsis: "Christmas week, and the whole family around one table spreading masa on corn husks. Learn the steps, keep up with Tía Lupe, and hear the stories that come out when everyone's hands are busy.",
      homeLines: { start: "The masa's ready. Tía Lupe needs another pair of hands.", going: "Tamales take all day. You're only halfway.", done: "Six dozen tamales, steaming. Next: Las Posadas." },
    },
    {
      n: 4,
      name: "Las Posadas",
      native: "Las Posadas",
      subtitle: "Nine nights before Christmas",
      synopsis: "Walk the street with the neighbours, sing the verses asking for shelter, and finally break the piñata. A tradition that turns a street into a family.",
      homeLines: { start: "The procession leaves at sundown. Grab a candle.", going: "The posada's still going. The piñata is waiting.", done: "The piñata's in pieces and the ponche is warm. Next: Los Cuentos." },
    },
    {
      n: 5,
      name: "Los Cuentos",
      native: "Los Cuentos",
      subtitle: "Stories with the lights low",
      synopsis: "The power's out, the candles are lit, and Abuela tells the old story of the rabbit in the moon.",
      homeLines: { start: "The lights are out. Abuela's lighting candles.", going: "Abuela's story isn't finished yet.", done: "Now you'll see the rabbit every full moon. Next: La Familia." },
    },
    {
      n: 6,
      name: "La Familia",
      native: "La Familia",
      subtitle: "Two homes, one family",
      synopsis: "A video call to the cousins in the pueblo, and a family photo that stretches across two countries. Use everything you've learned.",
      homeLines: { start: "The cousins are calling from Michoacán.", going: "Everyone's still on the call.", done: "Two homes, one family. You've finished the Spanish journey." },
    }
  ],
  highlight: { native: "¿Y quién es él?", roman: "", english: "And who is he?", context: "Abuela points to the photo at the top of the ofrenda. By then, you know the answer." },
};

export default meta;
