import type { Language } from "../types";

/* HINDI · Devanagari · A Hindi-speaking family from Lucknow. */

const meta: Language = {
  id: "hindi",
  lang: "hi",
  speech: "hi",
  language: "Hindi",
  native: "हिन्दी",
  family: "A Hindi-speaking family from Lucknow",
  variety: "Hindi · Devanagari script",
  script: "hi",
  romanize: true,
  line: "A family from Lucknow, from Dadi's summer visit to Holi in her city — with room for every region's differences.",
  journeys: ["Family conversations", "Food and festivals", "Music and stories", "Regional traditions"],
  a: "#e07a2f",
  b: "#1f4d33",
  rank: 3,
  cover: 4,
  speakers: {
    dadi: { name: "Dadi", glyph: "दा", tone: "elder" },
    maa: { name: "Maa", glyph: "माँ", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    { id: "paani", native: "पानी", roman: "paani", english: "water", group: "food", where: "the kitchen tap", ch: 1 },
    { id: "doodh", native: "दूध", roman: "doodh", english: "milk", group: "food", where: "the fridge", ch: 1 },
    { id: "cheeni", native: "चीनी", roman: "cheeni", english: "sugar", group: "food", where: "Maa's jar", ch: 1 },
    { id: "chai", native: "चाय", roman: "chai", english: "tea", group: "food", where: "the kitchen", ch: 1 },
    { id: "adrak", native: "अदरक", roman: "adrak", english: "ginger", group: "food", where: "the kitchen", ch: 1 },
    { id: "ghar", native: "घर", roman: "ghar", english: "home · house", group: "home", where: "the living-room window", ch: 1 },
    { id: "chashma", native: "चश्मा", roman: "chashma", english: "glasses", group: "home", where: "Dadi's room", ch: 1 },
    { id: "kahaani", native: "कहानी", roman: "kahaani", english: "story", group: "home", where: "Dadi's storybook", ch: 1 },
    { id: "maa", native: "माँ", roman: "maa", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "papa", native: "पापा", roman: "papa", english: "dad", group: "family", where: "his cricket match", ch: 1 },
    { id: "dadi", native: "दादी", roman: "daadi", english: "grandma (dad's mother)", group: "family", where: "the living room", ch: 1 },
    { id: "dada", native: "दादा", roman: "daada", english: "grandpa (dad's father)", group: "family", where: "the photo over the sofa", ch: 1 },
    { id: "parivaar", native: "परिवार", roman: "parivaar", english: "family", group: "family", where: "the photos in Dadi's room", ch: 1 },
    { id: "baazaar", native: "बाज़ार", roman: "baazaar", english: "market · bazaar", group: "home", where: "Aminabad, Lucknow", ch: 2 },
    { id: "aaloo", native: "आलू", roman: "aaloo", english: "potato", group: "food", where: "Ramesh bhaiya's cart", ch: 2 },
    { id: "pyaaz", native: "प्याज़", roman: "pyaaz", english: "onion", group: "food", where: "Ramesh bhaiya's cart", ch: 2 },
    { id: "tamaatar", native: "टमाटर", roman: "tamaatar", english: "tomato", group: "food", where: "Ramesh bhaiya's cart", ch: 2 },
    { id: "neemboo", native: "नींबू", roman: "neemboo", english: "lemon · lime", group: "food", where: "Ramesh bhaiya's cart", ch: 2 },
    { id: "golgappe", native: "गोलगप्पे", roman: "golgappe", english: "golgappe — crisp hollow puris with spiced water", group: "food", where: "the chaat stall", ch: 2 },
    { id: "rupaye", native: "रुपये", roman: "rupaye", english: "rupees", group: "home", where: "paying in the bazaar", ch: 2 },
    { id: "do", native: "दो", roman: "do", english: "two", group: "home", where: "paying in the bazaar", ch: 2 },
    { id: "teen", native: "तीन", roman: "teen", english: "three", group: "home", where: "paying in the bazaar", ch: 2 },
    { id: "paanch", native: "पाँच", roman: "paanch", english: "five", group: "home", where: "paying in the bazaar", ch: 2 },
    { id: "das", native: "दस", roman: "das", english: "ten", group: "home", where: "paying in the bazaar", ch: 2 },
    { id: "kitne", native: "कितने का?", roman: "kitne ka?", english: "how much?", group: "home", where: "Dadi's bargaining", ch: 2 },
    { id: "mahanga", native: "बहुत महँगा", roman: "bahut mahanga", english: "too expensive", group: "home", where: "the chikan shop", ch: 2 },
    { id: "shukriya", native: "शुक्रिया", roman: "shukriya", english: "thank you", group: "home", where: "the chikan shop", ch: 2 },
    { id: "rasoi", native: "रसोई", roman: "rasoi", english: "kitchen", group: "home", where: "Dadi's house in Lucknow", ch: 3 },
    { id: "chaachi", native: "चाची", roman: "chaachi", english: "aunt (dad's brother's wife)", group: "family", where: "the kitchen", ch: 3 },
    { id: "behen", native: "बहन", roman: "behen", english: "sister · girl cousin", group: "family", where: "the courtyard", ch: 3 },
    { id: "aata", native: "आटा", roman: "aata", english: "wheat flour · dough", group: "food", where: "the steel tin", ch: 3 },
    { id: "ghee", native: "घी", roman: "ghee", english: "ghee", group: "food", where: "the brass pot", ch: 3 },
    { id: "belan", native: "बेलन", roman: "belan", english: "rolling pin", group: "home", where: "the counter", ch: 3 },
    { id: "tawa", native: "तवा", roman: "tawa", english: "griddle", group: "home", where: "the stove", ch: 3 },
    { id: "aag", native: "आग", roman: "aag", english: "fire · flame", group: "home", where: "the stove", ch: 3 },
    { id: "roti", native: "रोटी", roman: "roti", english: "roti — flatbread", group: "food", where: "the stack in the cloth", ch: 3 },
    { id: "gol", native: "गोल", roman: "gol", english: "round", group: "home", where: "your roti", ch: 3 },
    { id: "daal", native: "दाल", roman: "daal", english: "lentils", group: "food", where: "lunch", ch: 3 },
    { id: "chaawal", native: "चावल", roman: "chaawal", english: "rice", group: "food", where: "lunch", ch: 3 },
    { id: "holi", native: "होली", roman: "holi", english: "Holi — the festival of colours", group: "home", where: "the lane", ch: 4 },
    { id: "rang", native: "रंग", roman: "rang", english: "colour", group: "home", where: "the lane", ch: 4 },
    { id: "laal", native: "लाल", roman: "laal", english: "red", group: "home", where: "the gulaal trays", ch: 4 },
    { id: "hara", native: "हरा", roman: "hara", english: "green", group: "home", where: "the gulaal trays", ch: 4 },
    { id: "peela", native: "पीला", roman: "peela", english: "yellow", group: "home", where: "the gulaal trays", ch: 4 },
    { id: "neela", native: "नीला", roman: "neela", english: "blue", group: "home", where: "the gulaal trays", ch: 4 },
    { id: "gulaal", native: "गुलाल", roman: "gulaal", english: "gulaal — coloured powder", group: "home", where: "the gulaal trays", ch: 4 },
    { id: "pichkaari", native: "पिचकारी", roman: "pichkaari", english: "water squirter", group: "home", where: "Rohan's hands", ch: 4 },
    { id: "bhaai", native: "भाई", roman: "bhaai", english: "brother · boy cousin", group: "family", where: "the rooftop", ch: 4 },
    { id: "gujiya", native: "गुजिया", roman: "gujiya", english: "gujiya — sweet stuffed dumplings", group: "food", where: "Chachi's plates", ch: 4 },
    { id: "chaar", native: "चार", roman: "chaar", english: "four", group: "home", where: "Chachi's plates", ch: 4 },
    { id: "chhah", native: "छह", roman: "chhah", english: "six", group: "home", where: "Chachi's plates", ch: 4 },
    { id: "chhat", native: "छत", roman: "chhat", english: "roof", group: "home", where: "the stairs up", ch: 5 },
    { id: "chaand", native: "चाँद", roman: "chaand", english: "moon", group: "home", where: "over the roof", ch: 5 },
    { id: "taare", native: "तारे", roman: "taare", english: "stars", group: "home", where: "over the roof", ch: 5 },
    { id: "baadshaah", native: "बादशाह", roman: "baadshaah", english: "emperor", group: "home", where: "Dadi's story", ch: 5 },
    { id: "thand", native: "ठंड", roman: "thand", english: "cold", group: "home", where: "Dadi's story", ch: 5 },
    { id: "khichdi", native: "खिचड़ी", roman: "khichdi", english: "khichdi — rice and lentils cooked together", group: "food", where: "Dadi's story", ch: 5 },
    { id: "haandi", native: "हाँडी", roman: "haandi", english: "cooking pot", group: "home", where: "Dadi's story", ch: 5 },
    { id: "inaam", native: "इनाम", roman: "inaam", english: "reward", group: "home", where: "Dadi's story", ch: 5 },
    { id: "chatur", native: "चतुर", roman: "chatur", english: "clever", group: "home", where: "Dadi's story", ch: 5 },
    { id: "saamaan", native: "सामान", roman: "saamaan", english: "luggage · things", group: "home", where: "your room", ch: 6 },
    { id: "yaadein", native: "यादें", roman: "yaadein", english: "memories", group: "home", where: "your suitcase", ch: 6 },
    { id: "chaacha", native: "चाचा", roman: "chaacha", english: "uncle (dad's younger brother)", group: "family", where: "the video call", ch: 6 },
    { id: "bua", native: "बुआ", roman: "bua", english: "aunt (dad's sister)", group: "family", where: "the video call", ch: 6 },
    { id: "jaldi", native: "जल्दी", roman: "jaldi", english: "soon · quickly", group: "home", where: "saying goodbye", ch: 6 },
    { id: "yaad", native: "याद आएगी", roman: "yaad aayegi", english: "(I'll) miss you", group: "family", where: "saying goodbye", ch: 6 },
    { id: "phirmilenge", native: "फिर मिलेंगे", roman: "phir milenge", english: "see you again", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    pranam: { title: "Touching an elder's feet", native: "पैर छूना", note: "A greeting of respect in many North Indian families. The elder answers with a blessing — जीते रहो, live long." },
    mithai: { title: "Mithai from Lucknow", native: "मिठाई", note: "Sweets carried across an ocean in a suitcase. Every visiting grandparent's first priority." },
    chai: { title: "Masala chai", native: "चाय", note: "Boiled, not steeped: water, ginger, tea, milk, sugar. Every family does it slightly differently, and every family is right." },
    dabba: { title: "Masala dabba", native: "मसालेदानी", note: "A round steel tin with seven small cups of spice inside." },
    blockprint: { title: "Block-print bedspread", note: "Printed by hand with carved wooden blocks in Jaipur." },
    diya: { title: "The diya", native: "दिया", note: "A small brass lamp Dadi lights every evening, wherever she is." },
    panchatantra: { title: "The Panchatantra", native: "पंचतंत्र", note: "A collection of animal fables around two thousand years old. The monkey and the crocodile is one of the best known." },
    aminabad: { title: "Aminabad", native: "अमीनाबाद", note: "One of Lucknow's oldest bazaars — a maze of lanes selling everything from chikan kurtas to brass pots to kebabs." },
    golgappe: { title: "One snack, many names", native: "गोलगप्पे", note: "Golgappe in Lucknow and Delhi, pani puri in Mumbai, puchka in Kolkata. Same crisp shell, same argument about who makes them best." },
    chikan: { title: "Chikankari", native: "चिकनकारी", note: "Lucknow's delicate white-on-white embroidery, stitched by hand. A single kurta can take weeks." },
    molbhav: { title: "Mol-bhaav", native: "मोल-भाव", note: "Bargaining. In a bazaar, the first price is an opening line, not a price." },
    roti: { title: "Roti on the flame", native: "फुलका", note: "Cooked on the tawa, then held over an open flame until it puffs up like a balloon. A puffed roti means the dough was right." },
    chauka: { title: "Eating together", native: "एक साथ खाना", note: "Lunch at Dadi's is on the floor, everyone in a circle, dishes in the middle. Nobody eats until everyone's served." },
    holi: { title: "Holi", native: "होली", note: "The spring festival of colours. The night before, a bonfire for Holika; in the morning, everyone is fair game." },
    buranamaano: { title: "“Bura na maano, Holi hai!”", native: "बुरा न मानो, होली है!", note: "“Don't be offended — it's Holi!” The one line that excuses absolutely everything, one day a year." },
    gujiya: { title: "Gujiya", native: "गुजिया", note: "Crescent-shaped pastries filled with khoya, coconut and nuts, fried and made by the hundred for Holi." },
    thandai: { title: "Thandai", native: "ठंडाई", note: "A cold milk drink with almonds, fennel, rose and saffron. The official drink of the afternoon after Holi." },
    birbal: { title: "Akbar and Birbal", native: "अकबर-बीरबल", note: "Birbal was one of the nine jewels of Emperor Akbar's court, four hundred years ago. Hundreds of stories are told about his wit." },
    chhat: { title: "Rooftops", native: "छत", note: "In summer and after festivals, North Indian families sleep, talk and fly kites on the flat roof. It's the other living room." },
  },
  memoryNotes: {
    chai: { title: "Made chai for Dadi", note: "Water, ginger, milk, sugar — added in Hindi, in the right order." },
    glasses: { title: "Found Dadi's glasses", note: "On top of her head. Every single time." },
    story: { title: "The monkey and the crocodile", note: "Dadi's story — a clever monkey and a very hungry river." },
    answered: { title: "“बहुत अच्छी, दादी!”", note: "Dadi asked how you liked her story. You told her — in Hindi." },
    paid: { title: "Paid in rupees", note: "Do, teen, paanch, das — counted out in the bazaar." },
    haggle: { title: "Watched Dadi bargain", note: "Twelve hundred became nine hundred. Dadi didn't blink." },
    shukriya: { title: "“बस, शुक्रिया!”", note: "The shopkeeper asked if you wanted anything else. You told him — in Hindi." },
    kitchen: { title: "Helped Chachi in the kitchen", note: "Aata, paani, ghee, belan — by ear." },
    roti: { title: "Made a roti", note: "Knead, roll, tawa, flame, ghee." },
    gol: { title: "“एकदम गोल!”", note: "Your roti came out perfectly round. Well — nearly." },
    colours: { title: "Found the colours", note: "Laal, hara, peela, neela — thrown, not memorised." },
    gujiya: { title: "Shared out the gujiya", note: "Two, four, six, ten — on every plate." },
    holi: { title: "“बुरा न मानो, होली है!”", note: "You splashed Sharma Aunty. It's Holi. She didn't mind." },
    khichdi: { title: "Birbal's khichdi", note: "Heard on the rooftop, under the moon." },
    chatur: { title: "“बहुत चतुर!”", note: "Dadi asked what Birbal was like. You knew." },
    keepsakes: { title: "Unpacked Lucknow", note: "A chikan kurta, a pink-stained T-shirt, a tin of gujiya." },
    call: { title: "Named everyone on the call", note: "Chacha, Chachi, Bua, Bhaiya, Anu." },
    retold: { title: "Told your trip in Hindi", note: "Golgappe, roti, Holi, khichdi — in order." },
    phirmilenge: { title: "“फिर मिलेंगे!”", note: "Not goodbye. We'll meet again." },
  },
  chapters: [
    {
      n: 1,
      name: "Dadi's Here",
      native: "दादी आईं",
      subtitle: "The first day of summer",
      synopsis:
        "Dadi has flown in from Lucknow for the whole summer. Greet her the way she was greeted as a girl, make her chai the way she likes it, find the glasses she's lost again — and settle in for her story about a monkey, a crocodile and a very sweet heart.",
      homeLines: {
        start: "Dadi's just arrived from Lucknow. She's waiting in the living room.",
        going: "Dadi's still waiting — for chai, for her glasses, for a story.",
        done: "Dadi's story is told, and she's promised another tomorrow. Next: the bazaar in Lucknow.",
      },
    },
    {
      n: 2,
      name: "The Bazaar",
      native: "बाज़ार",
      subtitle: "Chaat and bargaining",
      synopsis: "In Lucknow with Dadi. Follow her through the bazaar: count rupees, taste golgappe, and learn how to say “too expensive” like you mean it.",
      homeLines: { start: "Dadi's got her handbag. The bazaar is waiting.", going: "Dadi's still bargaining. Keep up.", done: "Bags full, chaat eaten. Next: Dadi's kitchen." },
    },
    {
      n: 3,
      name: "The Kitchen",
      native: "रसोई",
      subtitle: "Round rotis, eventually",
      synopsis: "Dadi's kitchen in Lucknow. Knead the dough, roll a roti, puff it on the flame — until one of them is actually round.",
      homeLines: { start: "Dadi's put out the rolling pin.", going: "The dough's ready. The rotis aren't.", done: "One round roti. Just one. Next: Holi." },
    },
    {
      n: 4,
      name: "Holi",
      native: "होली",
      subtitle: "The festival of colours",
      synopsis: "Gulal in every colour, water balloons, gujiya on a plate — learn the colours by throwing them, and why nobody minds going home a little pink.",
      homeLines: { start: "The courtyard's full. Everyone has gulal.", going: "There's still someone who isn't pink yet.", done: "Every colour, everywhere. Next: stories." },
    },
    {
      n: 5,
      name: "Stories",
      native: "कहानियाँ",
      subtitle: "Akbar and Birbal",
      synopsis: "On the rooftop after Holi, Dadi tells the story of Birbal's khichdi — the clever minister who cooked a pot of rice to teach an emperor a lesson.",
      homeLines: { start: "Dadi's on the rooftop with her chai.", going: "Birbal's khichdi still isn't cooked.", done: "Birbal wins again. Next: family." },
    },
    {
      n: 6,
      name: "Family",
      native: "परिवार",
      subtitle: "The call home",
      synopsis: "Home again. A video call to Lucknow — Chachi, the cousins, and one very loud uncle. Put names to everyone in the family, in Hindi.",
      homeLines: { start: "The whole Lucknow family is calling.", going: "Everyone's still talking at once.", done: "Everyone has a name now. You've finished the Hindi journey." },
    }
  ],
  highlight: { native: "कहानी कैसी लगी?", roman: "kahaani kaisi lagi?", english: "How did you like the story?", context: "Dadi asks after her story. You answer without looking anything up." },
};

export default meta;
