import type { Language } from "../types";

/* FRENCH · A family from Lyon. Six chapters, from Mamie's crêpes to a video call across the Atlantic. */

const meta: Language = {
  id: "french",
  lang: "fr-FR",
  speech: "fr",
  language: "French",
  native: "Français",
  family: "A French family from Lyon",
  variety: "French · as spoken in Lyon",
  script: "latin",
  romanize: false,
  line: "A family from Lyon, from Mamie's crêpes to a galette with a secret inside. One French-speaking world of many.",
  journeys: ["Family meals and the goûter", "Festivals through the French year", "Fables, songs and nursery rhymes", "Other French-speaking families — Québec, Senegal, Belgium, the Caribbean"],
  a: "#3a5a9a",
  b: "#b8452f",
  rank: 5,
  speakers: {
    mamie: { name: "Mamie", glyph: "M", tone: "elder" },
    papi: { name: "Papi", glyph: "P", tone: "elder" },
    maman: { name: "Maman", glyph: "M", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    // ch1 — le goûter
    { id: "mamie", native: "Mamie", roman: "Mamie", english: "grandma", group: "family", where: "the front hall", ch: 1 },
    { id: "maman", native: "maman", roman: "maman", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "papa", native: "papa", roman: "papa", english: "dad", group: "family", where: "the airport run", ch: 1 },
    { id: "famille", native: "famille", roman: "famille", english: "family", group: "family", where: "the photos in the hall", ch: 1 },
    { id: "maison", native: "maison", roman: "maison", english: "home · house", group: "home", where: "the front door", ch: 1 },
    { id: "bonjour", native: "bonjour", roman: "bonjour", english: "hello · good morning", group: "home", where: "the front door", ch: 1 },
    { id: "valise", native: "valise", roman: "valise", english: "suitcase", group: "home", where: "Mamie's luggage", ch: 1 },
    { id: "confiture", native: "confiture", roman: "confiture", english: "jam", group: "food", where: "Mamie's suitcase", ch: 1 },
    { id: "farine", native: "farine", roman: "farine", english: "flour", group: "food", where: "the kitchen cupboard", ch: 1 },
    { id: "oeufs", native: "œufs", roman: "œufs", english: "eggs", group: "food", where: "the fridge", ch: 1 },
    { id: "lait", native: "lait", roman: "lait", english: "milk", group: "food", where: "the fridge", ch: 1 },
    { id: "sucre", native: "sucre", roman: "sucre", english: "sugar", group: "food", where: "the kitchen cupboard", ch: 1 },
    { id: "poele", native: "poêle", roman: "poêle", english: "frying pan", group: "home", where: "the stove", ch: 1 },
    { id: "crepe", native: "crêpe", roman: "crêpe", english: "crêpe", group: "food", where: "Mamie's pan", ch: 1 },
    { id: "silteplait", native: "s'il te plaît", roman: "s'il te plaît", english: "please", group: "home", where: "the goûter table", ch: 1 },
    // ch2 — le village
    { id: "papi", native: "Papi", roman: "Papi", english: "grandpa", group: "family", where: "the village house", ch: 2 },
    { id: "village", native: "village", roman: "village", english: "village", group: "home", where: "the Monts du Lyonnais", ch: 2 },
    { id: "fontaine", native: "fontaine", roman: "fontaine", english: "fountain", group: "home", where: "the village square", ch: 2 },
    { id: "boulangerie", native: "boulangerie", roman: "boulangerie", english: "bakery", group: "home", where: "the village square", ch: 2 },
    { id: "baguette", native: "baguette", roman: "baguette", english: "baguette", group: "food", where: "the bakery", ch: 2 },
    { id: "croissant", native: "croissant", roman: "croissant", english: "croissant", group: "food", where: "the bakery", ch: 2 },
    { id: "painchoc", native: "pain au chocolat", roman: "pain au chocolat", english: "chocolate croissant", group: "food", where: "the bakery", ch: 2 },
    { id: "un", native: "un", roman: "un", english: "one", group: "home", where: "the pétanque ground", ch: 2 },
    { id: "deux", native: "deux", roman: "deux", english: "two", group: "home", where: "the pétanque ground", ch: 2 },
    { id: "trois", native: "trois", roman: "trois", english: "three", group: "home", where: "the pétanque ground", ch: 2 },
    { id: "quatre", native: "quatre", roman: "quatre", english: "four", group: "home", where: "the pétanque ground", ch: 2 },
    { id: "boules", native: "boules", roman: "boules", english: "pétanque balls", group: "home", where: "the pétanque ground", ch: 2 },
    { id: "toutdroit", native: "tout droit", roman: "tout droit", english: "straight ahead", group: "home", where: "directions in the village", ch: 2 },
    { id: "gauche", native: "à gauche", roman: "à gauche", english: "on the left", group: "home", where: "directions in the village", ch: 2 },
    { id: "droite", native: "à droite", roman: "à droite", english: "on the right", group: "home", where: "directions in the village", ch: 2 },
    // ch3 — le marché
    { id: "marche", native: "marché", roman: "marché", english: "market", group: "home", where: "the Croix-Rousse", ch: 3 },
    { id: "fromage", native: "fromage", roman: "fromage", english: "cheese", group: "food", where: "the cheese stall", ch: 3 },
    { id: "tomates", native: "tomates", roman: "tomates", english: "tomatoes", group: "food", where: "Monsieur Paul's stall", ch: 3 },
    { id: "peches", native: "pêches", roman: "pêches", english: "peaches", group: "food", where: "Monsieur Paul's stall", ch: 3 },
    { id: "fraises", native: "fraises", roman: "fraises", english: "strawberries", group: "food", where: "Monsieur Paul's stall", ch: 3 },
    { id: "melon", native: "melon", roman: "melon", english: "melon", group: "food", where: "Monsieur Paul's stall", ch: 3 },
    { id: "euro", native: "euro", roman: "euro", english: "euro", group: "home", where: "paying at the market", ch: 3 },
    { id: "cinq", native: "cinq", roman: "cinq", english: "five", group: "home", where: "paying at the market", ch: 3 },
    { id: "dix", native: "dix", roman: "dix", english: "ten", group: "home", where: "paying at the market", ch: 3 },
    { id: "combien", native: "c'est combien ?", roman: "c'est combien ?", english: "how much is it?", group: "home", where: "the cheese stall", ch: 3 },
    { id: "merci", native: "merci", roman: "merci", english: "thank you", group: "home", where: "the cheese stall", ch: 3 },
    // ch4 — la galette des rois
    { id: "galette", native: "galette des rois", roman: "galette des rois", english: "kings' cake", group: "food", where: "Mamie's table in January", ch: 4 },
    { id: "feve", native: "fève", roman: "fève", english: "the charm hidden in the galette", group: "home", where: "somebody's slice", ch: 4 },
    { id: "couronne", native: "couronne", roman: "couronne", english: "crown", group: "home", where: "on top of the galette box", ch: 4 },
    { id: "couteau", native: "couteau", roman: "couteau", english: "knife", group: "home", where: "the sideboard", ch: 4 },
    { id: "assiettes", native: "assiettes", roman: "assiettes", english: "plates", group: "home", where: "the sideboard", ch: 4 },
    { id: "part", native: "part", roman: "part", english: "slice · share", group: "food", where: "the galette", ch: 4 },
    { id: "cousin", native: "cousin", roman: "cousin", english: "cousin (boy)", group: "family", where: "the galette table", ch: 4 },
    { id: "cousine", native: "cousine", roman: "cousine", english: "cousin (girl)", group: "family", where: "the galette table", ch: 4 },
    { id: "pourqui", native: "c'est pour qui ?", roman: "c'est pour qui ?", english: "who is it for?", group: "home", where: "under the table", ch: 4 },
    { id: "moi", native: "c'est moi !", roman: "c'est moi !", english: "it's me!", group: "home", where: "the galette table", ch: 4 },
    // ch5 — les fables
    { id: "livre", native: "livre", roman: "livre", english: "book", group: "home", where: "Papi's shelf", ch: 5 },
    { id: "fable", native: "fable", roman: "fable", english: "fable", group: "home", where: "Papi's old schoolbook", ch: 5 },
    { id: "neige", native: "neige", roman: "neige", english: "snow", group: "home", where: "the balcony", ch: 5 },
    { id: "nuit", native: "nuit", roman: "nuit", english: "night", group: "home", where: "the balcony", ch: 5 },
    { id: "corbeau", native: "corbeau", roman: "corbeau", english: "crow", group: "home", where: "Papi's fable", ch: 5 },
    { id: "renard", native: "renard", roman: "renard", english: "fox", group: "home", where: "Papi's fable", ch: 5 },
    { id: "arbre", native: "arbre", roman: "arbre", english: "tree", group: "home", where: "Papi's fable", ch: 5 },
    { id: "bec", native: "bec", roman: "bec", english: "beak", group: "home", where: "Papi's fable", ch: 5 },
    { id: "chanter", native: "chanter", roman: "chanter", english: "to sing", group: "home", where: "Papi's fable", ch: 5 },
    { id: "flatteur", native: "flatteur", roman: "flatteur", english: "flatterer", group: "home", where: "Papi's fable", ch: 5 },
    { id: "malin", native: "malin", roman: "malin", english: "clever · cunning", group: "home", where: "after the fable", ch: 5 },
    // ch6 — la famille
    { id: "souvenir", native: "souvenir", roman: "souvenir", english: "keepsake · memory", group: "home", where: "your suitcase", ch: 6 },
    { id: "tonton", native: "tonton", roman: "tonton", english: "uncle", group: "family", where: "the video call", ch: 6 },
    { id: "tata", native: "tata", roman: "tata", english: "aunt", group: "family", where: "the video call", ch: 6 },
    { id: "bientot", native: "bientôt", roman: "bientôt", english: "soon", group: "home", where: "saying goodbye", ch: 6 },
    { id: "manques", native: "tu me manques", roman: "tu me manques", english: "I miss you (lit. “you are missing to me”)", group: "family", where: "saying goodbye", ch: 6 },
    { id: "bisous", native: "bisous", roman: "bisous", english: "kisses — how French families sign off", group: "family", where: "saying goodbye", ch: 6 },
    { id: "abientot", native: "à bientôt", roman: "à bientôt", english: "see you soon", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    bise: { title: "La bise", native: "la bise", note: "A kiss on each cheek to say hello. Two in Lyon; three or even four in other parts of France. Nobody agrees, and everybody has bumped noses." },
    gouter: { title: "Le goûter", native: "le goûter", note: "The four o'clock snack every French child gets after school: bread and chocolate, crêpes, a piece of fruit. Grown-ups pretend they're too old for it." },
    pralines: { title: "Pralines roses", native: "pralines roses", note: "Almonds in bright pink sugar — a Lyon speciality, baked into brioche and tarts. Mamie brings a bag every visit." },
    crepes: { title: "Flipping crêpes", native: "la Chandeleur", note: "On la Chandeleur in February, you flip a crêpe holding a coin in your other hand — for luck all year." },
    boulangerie: { title: "The boulangerie", native: "la boulangerie", note: "Bread bought fresh, often twice a day. The tip of the baguette — le quignon — rarely makes it home." },
    petanque: { title: "Pétanque", native: "la pétanque", note: "Throw your metal boules as close as you can to the little wooden cochonnet. Played in every village square, mostly by people who argue about measuring." },
    pierresdorees: { title: "Pierres dorées", native: "les pierres dorées", note: "North of Lyon, villages are built of a golden limestone that glows at sunset. Mamie grew up in one." },
    clocher: { title: "The church bell", native: "le clocher", note: "In many villages the bell rings the hour twice — once for the people who weren't listening the first time." },
    croixrousse: { title: "Marché de la Croix-Rousse", native: "la Croix-Rousse", note: "A market along the boulevard on Lyon's hill every morning but Monday. The silk-weavers of the 1800s once lived here." },
    bonjourfirst: { title: "Bonjour first", native: "bonjour", note: "In France, you say bonjour before anything else — to a shopkeeper, a bus driver, a doctor. Skip it and you'll be served very, very slowly." },
    stmarcellin: { title: "Saint-Marcellin", native: "le saint-marcellin", note: "A small, soft cow's-milk cheese from near Lyon, sold runny in little clay dishes. Lyonnais will argue about its perfect ripeness forever." },
    nobargain: { title: "No bargaining", native: "prix fixe", note: "French markets don't haggle. Prices are on little chalkboards. Being polite gets you the ripest peach instead." },
    galette: { title: "La galette des rois", native: "la galette des rois", note: "Puff pastry and frangipane, eaten in January for Epiphany. Somewhere inside is a fève — a tiny porcelain charm." },
    table: { title: "Under the table", native: "sous la table", note: "The youngest person hides under the table and calls out who gets each slice, so nobody can cheat their way to the fève." },
    feve: { title: "Collecting fèves", native: "les fèves", note: "Tiny porcelain figures — saints, animals, cartoon characters. Some people collect thousands. They have a name: fabophiles." },
    lafontaine: { title: "Jean de La Fontaine", native: "Les Fables", note: "Published in 1668. Nearly every French child learns “Le Corbeau et le Renard” by heart at school — and can still recite it at eighty." },
    fourviere: { title: "Fourvière", native: "Fourvière", note: "The white basilica on the hill above Lyon, lit up at night. Every December 8th, the whole city puts candles in its windows for it." },
  },
  memoryNotes: {
    bise: { title: "Faire la bise", note: "Two kisses for Mamie. Only one bumped nose." },
    batter: { title: "Helped Mamie with the batter", note: "Farine, œufs, lait, sucre — passed by ear." },
    crepes: { title: "Flipped a crêpe", note: "Mix, pour, flip, jam, fold." },
    silteplait: { title: "“Oui, s'il te plaît !”", note: "Mamie offered another crêpe. You said yes — nicely, in French." },
    bread: { title: "Bought bread for Papi", note: "Baguette, croissants, pains au chocolat." },
    petanque: { title: "Kept score at pétanque", note: "Un, deux, trois, quatre — Papi won. Probably." },
    directions: { title: "“Tout droit, puis à droite !”", note: "A cyclist asked the way. You told her — in French." },
    paid: { title: "Paid in euros", note: "Deux, trois, cinq, dix — at Monsieur Paul's stall." },
    bonjour: { title: "Said bonjour first", note: "And got the best Saint-Marcellin on the stall." },
    toutmerci: { title: "“Ce sera tout, merci !”", note: "The cheese seller asked “et avec ceci ?” You knew the answer." },
    set: { title: "Set the galette table", note: "Couteau, assiettes, couronne — for Papi." },
    parts: { title: "Called out the slices", note: "From under the table, fair and square." },
    feve: { title: "“C'est moi !”", note: "You found the fève. You wore the crown." },
    test: { title: "Beat Léa's word test", note: "On the balcony, in the snow." },
    fable: { title: "Le Corbeau et le Renard", note: "Papi recited it from memory, like he did at school." },
    malin: { title: "“Non, le renard était malin !”", note: "Papi asked if the crow was clever. You knew better." },
    keepsakes: { title: "Unpacked France", note: "A paper crown, a porcelain fève, a bag of pink pralines." },
    call: { title: "Named everyone on the call", note: "Tonton, Tata, ton cousin, ta cousine." },
    retold: { title: "Told your year in French", note: "Baguette, fromage, fève, renard — in order." },
    abientot: { title: "“À bientôt !”", note: "Not goodbye. See you soon. Bisous." },
  },
  chapters: [
    {
      n: 1,
      name: "Le Goûter",
      native: "Le Goûter",
      subtitle: "Mamie arrives from Lyon",
      synopsis: "Mamie has flown in from Lyon with a suitcase that smells of jam. Greet her the French way, help her with the batter, flip your first crêpe — and learn how to ask for another one.",
      homeLines: {
        start: "Mamie's just arrived from Lyon. She's in the front hall with her suitcase.",
        going: "The crêpe batter's resting. Mamie's waiting for you.",
        done: "The goûter's eaten and the pan's still warm. Next: Papi's village.",
      },
    },
    {
      n: 2,
      name: "Le Village",
      native: "Le Village",
      subtitle: "Bread, boules and directions",
      synopsis: "Summer in Mamie and Papi's village of golden stone. Buy the bread, keep score at pétanque under the plane trees, and help a lost cyclist find her way.",
      homeLines: { start: "Papi needs bread, and the boulangerie closes at noon.", going: "The pétanque game is still going.", done: "The bread's home and Papi won. Probably. Next: the market in Lyon." },
    },
    {
      n: 3,
      name: "Le Marché",
      native: "Le Marché",
      subtitle: "Saturday at the Croix-Rousse",
      synopsis: "Mamie's Saturday market on the hill in Lyon. Fill the basket by ear, count out euros, learn why bonjour always comes first — and answer the question every French shopkeeper asks.",
      homeLines: { start: "Mamie's basket is by the door. It's market day.", going: "The market's busy, and Mamie still has a list.", done: "Basket full, cheese chosen. Next: the galette des rois." },
    },
    {
      n: 4,
      name: "La Galette des Rois",
      native: "La Galette des Rois",
      subtitle: "A cake with a secret",
      synopsis: "January, back in Lyon. Somewhere in Mamie's galette is a tiny porcelain fève. Set the table, call out the slices from under it — and find out who gets to wear the crown.",
      homeLines: { start: "Mamie's galette is out of the oven.", going: "Nobody's found the fève yet.", done: "The fève is found and the crown is on. Next: Papi's fable." },
    },
    {
      n: 5,
      name: "Les Fables",
      native: "Les Fables",
      subtitle: "The crow and the fox",
      synopsis: "A snowy evening in Lyon. Papi takes down his old schoolbook and recites the fable every French child learns by heart: a crow, a fox, and a very nice piece of cheese.",
      homeLines: { start: "Papi has his old schoolbook out.", going: "The fox is still talking to the crow.", done: "Now you know the fable too. Next: the family." },
    },
    {
      n: 6,
      name: "La Famille",
      native: "La Famille",
      subtitle: "Calling Lyon",
      synopsis: "Home again. A video call to Lyon: Tonton, Tata, and cousins who've missed you. Put names to everyone, tell your whole year in French — and sign off the way French families do.",
      homeLines: { start: "Lyon is calling.", going: "Everyone's still on the call.", done: "À bientôt, Lyon. You've finished the French journey." },
    },
  ],
  highlight: { native: "C'est moi !", roman: "", english: "It's me!", context: "When everyone asks who found the fève in Mamie's galette — and it's you." },
};

export default meta;
