import type { Language } from "../types";

/* URDU · Nastaliq, right to left · A Pakistani family from Lahore. Six chapters, from Dadi's parcel to Eid in the old city. */

const meta: Language = {
  id: "urdu",
  lang: "ur",
  speech: "ur",
  language: "Urdu",
  native: "اردو",
  family: "A Pakistani family from Lahore",
  variety: "Urdu · Nastaliq script, right to left",
  script: "ur",
  dir: "rtl",
  romanize: true,
  line: "A family from Lahore, from Dadi's parcel to Eid morning in the old city. One Urdu-speaking world of many.",
  journeys: ["Food, family and hospitality", "Eid and the festivals of the year", "Poetry, stories and songs", "Other Urdu-speaking families — Karachi, Hyderabad, London, Toronto"],
  a: "#1f5a3a",
  b: "#b8452f",
  rank: 10,
  speakers: {
    dadi: { name: "Dadi", glyph: "د", tone: "elder" },
    dada: { name: "Dada", glyph: "د", tone: "elder" },
    ammi: { name: "Ammi", glyph: "ا", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    // ch1 — پارسل
    { id: "dadi", native: "دادی", roman: "dadi", english: "grandma (dad's mother)", group: "family", where: "the video call", ch: 1 },
    { id: "ammi", native: "امی", roman: "ammi", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "abbu", native: "ابو", roman: "abbu", english: "dad", group: "family", where: "the front door", ch: 1 },
    { id: "khandan", native: "خاندان", roman: "khandan", english: "family · the whole clan", group: "family", where: "the photos in the hall", ch: 1 },
    { id: "ghar", native: "گھر", roman: "ghar", english: "home · house", group: "home", where: "the front door", ch: 1 },
    { id: "salam", native: "السلام علیکم", roman: "assalam-o-alaikum", english: "hello — “peace be upon you”", group: "home", where: "the video call", ch: 1 },
    { id: "parcel", native: "پارسل", roman: "parcel", english: "parcel", group: "home", where: "the front step", ch: 1 },
    { id: "aam", native: "آم", roman: "aam", english: "mango", group: "food", where: "Dadi's parcel", ch: 1 },
    { id: "chawal", native: "چاول", roman: "chawal", english: "rice", group: "food", where: "the kitchen cupboard", ch: 1 },
    { id: "doodh", native: "دودھ", roman: "doodh", english: "milk", group: "food", where: "the fridge", ch: 1 },
    { id: "cheeni", native: "چینی", roman: "cheeni", english: "sugar", group: "food", where: "the kitchen cupboard", ch: 1 },
    { id: "ilaichi", native: "الائچی", roman: "ilaichi", english: "cardamom", group: "food", where: "Dadi's parcel", ch: 1 },
    { id: "badam", native: "بادام", roman: "badam", english: "almonds", group: "food", where: "Dadi's parcel", ch: 1 },
    { id: "kheer", native: "کھیر", roman: "kheer", english: "kheer — rice pudding", group: "food", where: "the pot on the stove", ch: 1 },
    { id: "mazedaar", native: "مزے دار", roman: "mazedaar", english: "delicious", group: "food", where: "the first spoonful", ch: 1 },
    // ch2 — چھت
    { id: "dada", native: "دادا", roman: "dada", english: "grandpa (dad's father)", group: "family", where: "the rooftop", ch: 2 },
    { id: "mohalla", native: "محلہ", roman: "mohalla", english: "neighbourhood", group: "home", where: "the old city", ch: 2 },
    { id: "gali", native: "گلی", roman: "gali", english: "lane", group: "home", where: "the old city", ch: 2 },
    { id: "chhat", native: "چھت", roman: "chhat", english: "roof", group: "home", where: "the top of the haveli", ch: 2 },
    { id: "kabootar", native: "کبوتر", roman: "kabootar", english: "pigeon", group: "home", where: "Dada's pigeon loft", ch: 2 },
    { id: "dana", native: "دانہ", roman: "dana", english: "grain · birdseed", group: "home", where: "Dada's tin", ch: 2 },
    { id: "pani", native: "پانی", roman: "pani", english: "water", group: "food", where: "the clay bowl", ch: 2 },
    { id: "ek", native: "ایک", roman: "ek", english: "one", group: "home", where: "counting pigeons", ch: 2 },
    { id: "do", native: "دو", roman: "do", english: "two", group: "home", where: "counting pigeons", ch: 2 },
    { id: "teen", native: "تین", roman: "teen", english: "three", group: "home", where: "counting pigeons", ch: 2 },
    { id: "chaar", native: "چار", roman: "chaar", english: "four", group: "home", where: "counting pigeons", ch: 2 },
    { id: "zaroor", native: "ضرور", roman: "zaroor", english: "definitely · of course", group: "home", where: "the next rooftop", ch: 2 },
    // ch3 — انارکلی
    { id: "bazaar", native: "بازار", roman: "bazaar", english: "market", group: "home", where: "Anarkali", ch: 3 },
    { id: "choorian", native: "چوڑیاں", roman: "choorian", english: "glass bangles", group: "home", where: "the bangle stall", ch: 3 },
    { id: "laal", native: "لال", roman: "laal", english: "red", group: "home", where: "the bangle stall", ch: 3 },
    { id: "hara", native: "ہرا", roman: "hara", english: "green", group: "home", where: "the bangle stall", ch: 3 },
    { id: "sunehra", native: "سنہرا", roman: "sunehra", english: "golden", group: "home", where: "the bangle stall", ch: 3 },
    { id: "neela", native: "نیلا", roman: "neela", english: "blue", group: "home", where: "the bangle stall", ch: 3 },
    { id: "jalebi", native: "جلیبی", roman: "jalebi", english: "jalebi — a syrupy spiral sweet", group: "food", where: "the sweet stall", ch: 3 },
    { id: "rupay", native: "روپے", roman: "rupay", english: "rupees", group: "home", where: "paying in the bazaar", ch: 3 },
    { id: "paanch", native: "پانچ", roman: "paanch", english: "five", group: "home", where: "paying in the bazaar", ch: 3 },
    { id: "das", native: "دس", roman: "das", english: "ten", group: "home", where: "paying in the bazaar", ch: 3 },
    { id: "kitne", native: "کتنے کا ہے؟", roman: "kitne ka hai?", english: "how much is it?", group: "home", where: "the cloth shop", ch: 3 },
    { id: "mehnga", native: "بہت مہنگا", roman: "bohat mehnga", english: "too expensive", group: "home", where: "the cloth shop", ch: 3 },
    { id: "shukriya", native: "شکریہ", roman: "shukriya", english: "thank you", group: "home", where: "the cloth shop", ch: 3 },
    // ch4 — عید
    { id: "eid", native: "عید", roman: "eid", english: "Eid", group: "home", where: "the end of Ramzan", ch: 4 },
    { id: "chaandraat", native: "چاند رات", roman: "chaand raat", english: "moon night — the eve of Eid", group: "home", where: "the rooftop", ch: 4 },
    { id: "chaand", native: "چاند", roman: "chaand", english: "moon", group: "home", where: "the western sky", ch: 4 },
    { id: "mehndi", native: "مہندی", roman: "mehndi", english: "henna", group: "home", where: "Phuppo's hands", ch: 4 },
    { id: "kapre", native: "نئے کپڑے", roman: "naye kapre", english: "new clothes", group: "home", where: "the cupboard", ch: 4 },
    { id: "sheerkhurma", native: "شیر خرما", roman: "sheer khurma", english: "sheer khurma — Eid vermicelli pudding", group: "food", where: "Dadi's big pot", ch: 4 },
    { id: "sewaiyan", native: "سویاں", roman: "sewaiyan", english: "vermicelli", group: "food", where: "the kitchen shelf", ch: 4 },
    { id: "khajoor", native: "کھجور", roman: "khajoor", english: "dates", group: "food", where: "the kitchen shelf", ch: 4 },
    { id: "eidi", native: "عیدی", roman: "eidi", english: "Eidi — the gift elders give on Eid", group: "family", where: "Dada's pocket", ch: 4 },
    { id: "eidmubarak", native: "عید مبارک", roman: "eid mubarak", english: "Eid Mubarak — blessed Eid", group: "home", where: "everybody, all day", ch: 4 },
    // ch5 — پیاسا کوا
    { id: "kahani", native: "کہانی", roman: "kahani", english: "story", group: "home", where: "the charpai", ch: 5 },
    { id: "dopahar", native: "دوپہر", roman: "dopahar", english: "afternoon", group: "home", where: "the hot rooftop", ch: 5 },
    { id: "garmi", native: "گرمی", roman: "garmi", english: "heat", group: "home", where: "the hot rooftop", ch: 5 },
    { id: "kawwa", native: "کوا", roman: "kawwa", english: "crow", group: "home", where: "the water tank", ch: 5 },
    { id: "pyasa", native: "پیاسا", roman: "pyasa", english: "thirsty", group: "home", where: "Dada's story", ch: 5 },
    { id: "ghara", native: "گھڑا", roman: "ghara", english: "clay water pot", group: "home", where: "Dada's story", ch: 5 },
    { id: "kankar", native: "کنکر", roman: "kankar", english: "pebbles", group: "home", where: "Dada's story", ch: 5 },
    { id: "hoshiyar", native: "ہوشیار", roman: "hoshiyar", english: "clever · smart", group: "home", where: "after the story", ch: 5 },
    // ch6 — خاندان
    { id: "yaadgaar", native: "یادگار", roman: "yaadgaar", english: "keepsake", group: "home", where: "your suitcase", ch: 6 },
    { id: "chacha", native: "چچا", roman: "chacha", english: "uncle (dad's brother)", group: "family", where: "the video call", ch: 6 },
    { id: "phuppo", native: "پھوپھو", roman: "phuppo", english: "aunt (dad's sister)", group: "family", where: "the video call", ch: 6 },
    { id: "mamoon", native: "ماموں", roman: "mamoon", english: "uncle (mom's brother)", group: "family", where: "the video call", ch: 6 },
    { id: "khala", native: "خالہ", roman: "khala", english: "aunt (mom's sister)", group: "family", where: "the video call", ch: 6 },
    { id: "shaadi", native: "شادی", roman: "shaadi", english: "wedding", group: "family", where: "the invitation card", ch: 6 },
    { id: "jald", native: "جلد", roman: "jald", english: "soon", group: "home", where: "saying goodbye", ch: 6 },
    { id: "yaad", native: "یاد آئے گی", roman: "yaad aaye gi", english: "(I'll) miss you", group: "family", where: "saying goodbye", ch: 6 },
    { id: "allahhafiz", native: "اللہ حافظ", roman: "Allah hafiz", english: "goodbye — “God keep you”", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    parcel: { title: "The parcel from home", native: "پارسل", note: "Every family abroad knows the parcel: taped on every side, stamped in three places, and full of spices, clothes and something sticky that leaked." },
    mangoes: { title: "Pakistani mangoes", native: "آم", note: "Chaunsa, Sindhri, Anwar Ratol — Pakistanis argue about mango varieties the way other people argue about football." },
    kheer: { title: "Kheer", native: "کھیر", note: "Rice slow-cooked in milk until it's thick and sweet, with cardamom and almonds. Made for every happy occasion — and most ordinary Fridays." },
    androon: { title: "Androon Lahore", native: "اندرون لاہور", note: "The walled old city, with thirteen gates and lanes so narrow you can touch both walls. Families have lived in the same havelis for generations." },
    kabootar: { title: "Pigeon keepers", native: "کبوتر باز", note: "On the rooftops of old Lahore, men keep flocks of pigeons and whistle them home at sunset. Dada's grandfather kept them too." },
    anarkali: { title: "Anarkali Bazaar", native: "انارکلی", note: "One of the oldest markets in South Asia, named after a legendary court dancer. Bangles, fabric, shoes, sweets — and crowds, always." },
    choorian: { title: "Glass bangles", native: "چوڑیاں", note: "Bought by the dozen before Eid and weddings. Chaand raat, the night before Eid, is when every girl and woman in the bazaar gets new ones." },
    jalebi: { title: "Hot jalebi", native: "جلیبی", note: "Batter piped in spirals into hot oil, then dunked in syrup. Eaten hot, standing up, in a paper bag." },
    chaandraat: { title: "Chaand raat", native: "چاند رات", note: "The night the new moon is sighted and Ramzan ends. Markets stay open till dawn: henna, bangles, last-minute clothes." },
    eidi: { title: "Eidi", native: "عیدی", note: "Crisp new banknotes that elders give the children on Eid. Kids compare totals by lunchtime." },
    galemilna: { title: "Eid hugs", native: "گلے ملنا", note: "On Eid you hug — right shoulder, left shoulder, right again — and say “Eid Mubarak” to everyone you meet." },
    sheerkhurma: { title: "Sheer khurma", native: "شیر خرما", note: "Vermicelli cooked in milk with dates, pistachios and almonds. The first thing everyone eats after the Eid prayer." },
    pyasakawwa: { title: "The Thirsty Crow", native: "پیاسا کوا", note: "Every child in Pakistan learns this story — originally one of Aesop's fables, told for so long it feels like it began here." },
    rishte: { title: "Chacha, phuppo, mamoon, khala", native: "رشتے", note: "Urdu has a different word for every aunt and uncle, depending on whether they're your father's family or your mother's." },
  },
  memoryNotes: {
    salam: { title: "Said salam to Dadi", note: "On a video call from Lahore, with the parcel on the table." },
    fetched: { title: "Found the kheer ingredients", note: "چاول، دودھ، چینی، الائچی — by ear." },
    kheer: { title: "Made Dadi's kheer", note: "Soak, boil, stir, sweeten, decorate." },
    mazedaar: { title: "“بہت مزے دار!”", note: "Dadi asked how the kheer turned out. You told her — in Urdu." },
    grain: { title: "Fed Dada's pigeons", note: "دانہ، پانی — on the rooftop at sunset." },
    pigeons: { title: "Counted the pigeons home", note: "ایک، دو، تین، چار." },
    zaroor: { title: "“ضرور!”", note: "The boy on the next roof asked if you'd meet again tomorrow." },
    bangles: { title: "Chose the Eid bangles", note: "لال، ہرا، سنہرا، نیلا." },
    paid: { title: "Paid in rupees", note: "دو، تین، پانچ، دس — at the jalebi stall." },
    shukriya: { title: "“بس، شکریہ!”", note: "The cloth seller asked if you wanted anything else." },
    chaandraat: { title: "Saw the Eid moon", note: "A thin silver line, and the whole city cheering." },
    eidmorning: { title: "Eid morning, in order", note: "New clothes, prayer, sheer khurma, hugs, eidi." },
    eidmubarak: { title: "“آپ کو بھی عید مبارک!”", note: "Dada gave you eidi. You wished him Eid Mubarak back." },
    test: { title: "Beat Zara's word test", note: "On the hot rooftop, in the shade." },
    story: { title: "The Thirsty Crow", note: "Dada's story, on the charpai, in the afternoon heat." },
    pebbles: { title: "Dropped the pebbles in", note: "Three, five, ten — and the water rose." },
    hoshiyar: { title: "“بہت ہوشیار!”", note: "Dada asked what the crow was like." },
    keepsakes: { title: "Unpacked Lahore", note: "Glass bangles, a box of jalebi, a tiny clay pot." },
    call: { title: "Named everyone on the call", note: "چچا، پھوپھو، ماموں، خالہ — which side is which." },
    retold: { title: "Told your trip in Urdu", note: "Pigeons, bangles, Eid, the crow — in order." },
    allahhafiz: { title: "“اللہ حافظ!”", note: "And a wedding to come back for." },
  },
  chapters: [
    {
      n: 1,
      name: "The Parcel",
      native: "پارسل",
      subtitle: "A box from Lahore",
      synopsis: "A parcel from Dadi in Lahore — mangoes, cardamom, and a recipe written in her own hand. Open it with her on a video call, gather what the recipe needs, and make her kheer for the first time.",
      homeLines: {
        start: "There's a parcel from Lahore on the front step.",
        going: "Dadi's still on the call, waiting for her kheer.",
        done: "The kheer is made and Dadi approves. Next: the rooftops of Lahore.",
      },
    },
    {
      n: 2,
      name: "The Rooftops",
      native: "چھت",
      subtitle: "Pigeons over the old city",
      synopsis: "Summer in Dada and Dadi's haveli in the walled city of Lahore. Climb to the roof, feed Dada's pigeons, count them home at sunset — and make a friend on the next roof.",
      homeLines: { start: "Dada's on the roof with his pigeons.", going: "The pigeons aren't all home yet.", done: "Every pigeon home. Next: Anarkali Bazaar." },
    },
    {
      n: 3,
      name: "Anarkali",
      native: "انارکلی",
      subtitle: "Bangles for Eid",
      synopsis: "The week before Eid in Anarkali Bazaar. Choose bangles by colour, count out rupees for hot jalebi, and watch Dadi bargain for Eid cloth.",
      homeLines: { start: "Dadi has her shopping bag and her bargaining face.", going: "The bazaar is packed, and Dadi still has a list.", done: "Bangles bought, cloth won. Next: Eid." },
    },
    {
      n: 4,
      name: "Eid",
      native: "عید",
      subtitle: "Moon night and morning",
      synopsis: "Watch for the moon on chaand raat, help Dadi with the sheer khurma, put Eid morning in the right order — and answer Dada properly when he hands you your eidi.",
      homeLines: { start: "Everyone's on the roof, watching for the moon.", going: "The sheer khurma is nearly ready.", done: "Eid Mubarak! Next: Dada's story." },
    },
    {
      n: 5,
      name: "The Thirsty Crow",
      native: "پیاسا کوا",
      subtitle: "A story in the afternoon heat",
      synopsis: "A blazing afternoon, a charpai in the shade, and Dada tells the story every Pakistani child knows: a crow, a pot, and a very good idea.",
      homeLines: { start: "Dada's on the charpai. It's too hot to move.", going: "The crow is still thirsty.", done: "The crow drank. Next: the family." },
    },
    {
      n: 6,
      name: "Family",
      native: "خاندان",
      subtitle: "Calling Lahore",
      synopsis: "Home again, with a wedding invitation in the post. A video call to Lahore: chacha, phuppo, mamoon, khala — a different word for every side. Tell your trip in Urdu, and say goodbye the Lahori way.",
      homeLines: { start: "Lahore is calling.", going: "Everyone's still on the call.", done: "اللہ حافظ! You've finished the Urdu journey." },
    },
  ],
  highlight: { native: "عید مبارک!", roman: "Eid mubarak!", english: "Blessed Eid!", context: "Said with a hug — right shoulder, left, right — to everyone on Eid morning. And Dada has your eidi ready." },
};

export default meta;
