import type { Language } from "../types";

/* TELUGU · A Telugu family in America, with roots in a village near Guntur.
   Where ROOTS began. Six chapters, from the family album at home to Sankranti
   in Ammamma's village and the goodbye that promises you'll come back. */

const meta: Language = {
  id: "telugu",
  lang: "te",
  speech: "te",
  language: "Telugu",
  native: "తెలుగు",
  family: "A Telugu family in America",
  variety: "Telugu",
  script: "te",
  romanize: true,
  line: "Where ROOTS began: from the family album at home to Sankranti in Ammamma's village near Guntur.",
  journeys: ["Telugu family life", "Sankranti and the harvest year", "Village, market and kitchen", "Folk stories under the banyan"],
  a: "#d9a441",
  b: "#9a4a2a",
  speakers: {
    amma: { name: "Amma", glyph: "అ", tone: "parent" },
    ammamma: { name: "Ammamma", glyph: "అ", tone: "elder" },
    tatayya: { name: "Tatayya", glyph: "తా", tone: "elder" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    { id: "neellu", native: "నీళ్ళు", roman: "neellu", english: "water", group: "food", where: "the glass on the desk", ch: 1 },
    { id: "illu", native: "ఇల్లు", roman: "illu", english: "home", group: "home", where: "the window", ch: 1 },
    { id: "pustakam", native: "పుస్తకం", roman: "pustakam", english: "book", group: "home", where: "the bookshelf", ch: 1 },
    { id: "photo", native: "ఫోటో", roman: "photo", english: "photo", group: "home", where: "the desk", ch: 1 },
    { id: "kutumbam", native: "కుటుంబం", roman: "kutumbam", english: "family", group: "family", where: "the hallway wall", ch: 1 },
    { id: "amma", native: "అమ్మ", roman: "amma", english: "mother", group: "family", where: "the hallway", ch: 1 },
    { id: "nanna", native: "నాన్న", roman: "nanna", english: "father", group: "family", where: "the hallway", ch: 1 },
    { id: "ammamma", native: "అమ్మమ్మ", roman: "ammamma", english: "grandmother (mother's mother)", group: "family", where: "the family album", ch: 1 },
    { id: "tatayya", native: "తాతయ్య", roman: "tatayya", english: "grandfather", group: "family", where: "the family album", ch: 1 },
    { id: "annam", native: "అన్నం", roman: "annam", english: "rice · food", group: "food", where: "the kitchen", ch: 1 },
    { id: "paalu", native: "పాలు", roman: "paalu", english: "milk", group: "food", where: "the kitchen", ch: 1 },
    { id: "uppu", native: "ఉప్పు", roman: "uppu", english: "salt", group: "food", where: "the kitchen", ch: 1 },
    { id: "namaskaram", native: "నమస్కారం", roman: "namaskaaram", english: "hello (with folded hands)", group: "home", where: "Ammamma's gate", ch: 2 },
    { id: "vepa", native: "వేప", roman: "vepa", english: "neem tree", group: "home", where: "Ammamma's yard", ch: 2 },
    { id: "ooru", native: "ఊరు", roman: "ooru", english: "village · hometown", group: "home", where: "the lane", ch: 2 },
    { id: "baavi", native: "బావి", roman: "baavi", english: "well", group: "home", where: "the lane", ch: 2 },
    { id: "aavu", native: "ఆవు", roman: "aavu", english: "cow", group: "home", where: "the lane", ch: 2 },
    { id: "taadu", native: "తాడు", roman: "taadu", english: "rope", group: "home", where: "the well", ch: 2 },
    { id: "binde", native: "బిందె", roman: "binde", english: "water pot", group: "home", where: "the well", ch: 2 },
    { id: "munduku", native: "ముందుకు", roman: "munduku", english: "straight ahead", group: "home", where: "Chinni's directions", ch: 2 },
    { id: "edama", native: "ఎడమ", roman: "edama", english: "left", group: "home", where: "Chinni's directions", ch: 2 },
    { id: "kudi", native: "కుడి", roman: "kudi", english: "right", group: "home", where: "Chinni's directions", ch: 2 },
    { id: "polam", native: "పొలం", roman: "polam", english: "field", group: "home", where: "the fields", ch: 2 },
    { id: "santha", native: "సంత", roman: "santha", english: "weekly market", group: "home", where: "the santha", ch: 3 },
    { id: "mamidi", native: "మామిడిపండు", roman: "maamidipandu", english: "mango", group: "food", where: "the fruit stall", ch: 3 },
    { id: "tomato", native: "టమాటా", roman: "tomaataa", english: "tomato", group: "food", where: "the vegetable stall", ch: 3 },
    { id: "arati", native: "అరటిపండు", roman: "aratipandu", english: "banana", group: "food", where: "the fruit stall", ch: 3 },
    { id: "nimma", native: "నిమ్మకాయ", roman: "nimmakaaya", english: "lemon", group: "food", where: "the fruit stall", ch: 3 },
    { id: "chintapandu", native: "చింతపండు", roman: "chintapandu", english: "tamarind", group: "food", where: "Subbarao garu's sacks", ch: 3 },
    { id: "roopaayi", native: "రూపాయి", roman: "roopaayi", english: "rupee", group: "home", where: "Lakshmamma's stall", ch: 3 },
    { id: "rendu", native: "రెండు", roman: "rendu", english: "two", group: "home", where: "paying at the santha", ch: 3 },
    { id: "moodu", native: "మూడు", roman: "moodu", english: "three", group: "home", where: "paying at the santha", ch: 3 },
    { id: "aidu", native: "అయిదు", roman: "aidu", english: "five", group: "home", where: "paying at the santha", ch: 3 },
    { id: "padi", native: "పది", roman: "padi", english: "ten", group: "home", where: "paying at the santha", ch: 3 },
    { id: "entha", native: "ఎంత", roman: "entha", english: "how much?", group: "home", where: "Ammamma's bargaining", ch: 3 },
    { id: "chaalu", native: "చాలు", roman: "chaalu", english: "enough", group: "home", where: "the tamarind stall", ch: 3 },
    { id: "bhogi", native: "భోగి", roman: "bhogi", english: "Bhogi — Sankranti's first day", group: "home", where: "the lane at dawn", ch: 4 },
    { id: "manta", native: "మంట", roman: "manta", english: "fire", group: "home", where: "the Bhogi fire", ch: 4 },
    { id: "muggu", native: "ముగ్గు", roman: "muggu", english: "muggu — the doorstep drawing", group: "home", where: "the gate", ch: 4 },
    { id: "chukkalu", native: "చుక్కలు", roman: "chukkalu", english: "dots", group: "home", where: "the muggu", ch: 4 },
    { id: "rangulu", native: "రంగులు", roman: "rangulu", english: "colours", group: "home", where: "the muggu", ch: 4 },
    { id: "gobbemma", native: "గొబ్బెమ్మ", roman: "gobbemma", english: "gobbemma — the flower mound on the muggu", group: "home", where: "the muggu", ch: 4 },
    { id: "bellam", native: "బెల్లం", roman: "bellam", english: "jaggery", group: "food", where: "Ammamma's kitchen", ch: 4 },
    { id: "pindi", native: "పిండి", roman: "pindi", english: "flour", group: "food", where: "Ammamma's kitchen", ch: 4 },
    { id: "nuvvulu", native: "నువ్వులు", roman: "nuvvulu", english: "sesame", group: "food", where: "Ammamma's kitchen", ch: 4 },
    { id: "nune", native: "నూనె", roman: "noone", english: "oil", group: "food", where: "Ammamma's kitchen", ch: 4 },
    { id: "ariselu", native: "అరిసెలు", roman: "ariselu", english: "ariselu — the Sankranti sweet", group: "food", where: "Ammamma's kitchen", ch: 4 },
    { id: "gaalipatam", native: "గాలిపటం", roman: "gaalipatam", english: "kite", group: "home", where: "the terrace", ch: 4 },
    { id: "daaram", native: "దారం", roman: "daaram", english: "string", group: "home", where: "the terrace", ch: 4 },
    { id: "gaali", native: "గాలి", roman: "gaali", english: "wind", group: "home", where: "the terrace", ch: 4 },
    { id: "panduga", native: "పండుగ", roman: "panduga", english: "festival", group: "home", where: "Sankranti", ch: 4 },
    { id: "katha", native: "కథ", roman: "katha", english: "story", group: "home", where: "under the banyan", ch: 5 },
    { id: "laantaru", native: "లాంతరు", roman: "laantaru", english: "lantern", group: "home", where: "the lane at dusk", ch: 5 },
    { id: "raatri", native: "రాత్రి", roman: "raatri", english: "night", group: "home", where: "the lane at dusk", ch: 5 },
    { id: "marri", native: "మర్రి చెట్టు", roman: "marri chettu", english: "banyan tree", group: "home", where: "the edge of the village", ch: 5 },
    { id: "pillalu", native: "పిల్లలు", roman: "pillalu", english: "children", group: "family", where: "under the banyan", ch: 5 },
    { id: "chandamaama", native: "చందమామ", roman: "chandamaama", english: "the moon", group: "home", where: "under the banyan", ch: 5 },
    { id: "nakshatraalu", native: "నక్షత్రాలు", roman: "nakshatraalu", english: "stars", group: "home", where: "under the banyan", ch: 5 },
    { id: "jnaapakam", native: "జ్ఞాపకం", roman: "jnaapakam", english: "keepsake · memory", group: "home", where: "your suitcase", ch: 6 },
    { id: "maavayya", native: "మావయ్య", roman: "maavayya", english: "uncle (mother's brother)", group: "family", where: "the video call", ch: 6 },
    { id: "pinni", native: "పిన్ని", roman: "pinni", english: "aunt (mother's younger sister)", group: "family", where: "the video call", ch: 6 },
    { id: "akka", native: "అక్క", roman: "akka", english: "older sister · older girl cousin", group: "family", where: "the video call", ch: 6 },
    { id: "tammudu", native: "తమ్ముడు", roman: "tammudu", english: "younger brother · younger boy cousin", group: "family", where: "the video call", ch: 6 },
    { id: "twaralo", native: "త్వరలో", roman: "twaralo", english: "soon", group: "home", where: "saying goodbye", ch: 6 },
    { id: "vellostaanu", native: "వెళ్ళొస్తాను", roman: "vellostaanu", english: "goodbye — “I'll go and come back”", group: "home", where: "saying goodbye", ch: 6 },
    { id: "malli", native: "మళ్ళీ", roman: "malli", english: "again", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    lamp: { title: "The brass lamp", native: "దీపం", note: "Ammamma's lamp. Lit every evening, even in a house eleven time zones from where it was made." },
    calendar: { title: "Temple calendar", native: "పంచాంగం", note: "From a temple in Guntur. Festival days circled by hand." },
    toran: { title: "Mango-leaf toran", native: "తోరణం", note: "Strung over a doorway to welcome. The leaves are changed for festivals." },
    tulasi: { title: "Tulasi plant", native: "తులసి", note: "Kept on the windowsill, watered every morning." },
    album: { title: "The family album", native: "ఆల్బమ్", note: "Found in the cupboard. Four generations, one shelf." },
    arugu: { title: "The arugu", native: "అరుగు", note: "The raised platform in front of a village house. Every evening, the whole street ends up sitting on someone's." },
    muggu: { title: "The daily muggu", native: "ముగ్గు", note: "Drawn at the gate before sunrise, in rice flour — a welcome for guests, and breakfast for the ants." },
    namaskaram: { title: "Namaskaram", native: "నమస్కారం", note: "Palms pressed together and a small bow: hello, thank you and respect, all at once." },
    cart: { title: "The bullock cart", native: "ఎడ్ల బండి", note: "Still how the harvest gets from field to house in plenty of villages." },
    gaajulu: { title: "Glass bangles", native: "గాజులు", note: "Sold by the dozen at every santha, in every colour." },
    tea: { title: "Santha chai", native: "టీ", note: "Poured from a height so it froths. Tatayya's stop, every market day." },
    beraam: { title: "Bargaining", native: "బేరం", note: "Nobody pays the first price at a santha. Ammamma never has." },
    gangireddu: { title: "Gangireddu", native: "గంగిరెద్దు", note: "A bull dressed in silk and bells, led house to house at Sankranti with music." },
    bhogi: { title: "The Bhogi fire", native: "భోగి మంట", note: "On Sankranti's first morning, old things go into the fire — out with what the year is finished with, in with the harvest." },
    gobbemma: { title: "Gobbemmalu", native: "గొబ్బెమ్మలు", note: "Small mounds of cow dung topped with flowers, set on the Sankranti muggu. Girls sing around them." },
    tenali: { title: "Tenali Ramakrishna", native: "తెనాలి రామకృష్ణుడు", note: "A poet in the court of King Krishnadevaraya, five hundred years ago — remembered for his wit in hundreds of stories." },
  },
  memoryNotes: {
    album: { title: "Family album assembled", note: "Amma, Nanna, Ammamma and Tatayya — placed by name, in Telugu." },
    kitchen: { title: "Helped Amma cook", note: "Water, salt, milk — fetched by ear, not by label." },
    understood: { title: "“I actually understood that.”", note: "Amma asked in Telugu. You answered in Telugu." },
    well: { title: "Drew water from the well", note: "Lower, pull, pour, lift — in Telugu." },
    directions: { title: "Found the way by asking", note: "Munduku, edamaki, kudiki — straight, left, right." },
    tinnava: { title: "“తిన్నాను, తాతయ్యా.”", note: "Tatayya asked if you'd eaten. You answered him in Telugu." },
    paid: { title: "Paid in rupees", note: "Two, three, five, ten — counted out in Telugu." },
    haggle: { title: "Watched Ammamma bargain", note: "Two hundred became a hundred and seventy." },
    chaalu: { title: "“చాలు, థాంక్స్!”", note: "You told the tamarind seller that's enough — in Telugu." },
    muggu: { title: "Drew the Sankranti muggu", note: "Dots, lines, colours, gobbemmalu." },
    ariselu: { title: "Made ariselu with Ammamma", note: "Rice flour, jaggery, sesame — and very sticky hands." },
    kite: { title: "Flew a kite with Tatayya", note: "The highest one on the street, for a minute." },
    sankranti: { title: "“సంక్రాంతి శుభాకాంక్షలు!”", note: "Shouted from the roof, and every roof shouted back." },
    story: { title: "Tenali Rama and the thieves", note: "Heard under the banyan, by lantern light." },
    nachchindi: { title: "“చాలా నచ్చింది!”", note: "You told Tatayya you loved his story." },
    keepsakes: { title: "Unpacked the village", note: "Bangles, ariselu, a kite with a torn tail." },
    call: { title: "Named everyone on the call", note: "Maavayya, Pinni, Akka, Tammudu." },
    retold: { title: "Told your summer in Telugu", note: "Well, santha, muggu, banyan — in order." },
    vellostaanu: { title: "“వెళ్ళొస్తాను!”", note: "I'll go — and I'll come back." },
  },
  chapters: [
    {
      n: 1,
      name: "A Family Story",
      native: "కుటుంబం",
      subtitle: "Where the journey starts",
      synopsis:
        "An ordinary American home with a Telugu family's story quietly everywhere in it. Amma is on the phone with Ammamma, and the old family album has gone missing. Find it, put four generations back in their places, help in the kitchen — and answer Amma in Telugu without stopping to think.",
      homeLines: {
        start: "Your first journey starts at home. Somewhere in the house is a family album.",
        going: "Amma is still waiting in the living room. The album hasn't found itself.",
        done: "Chapter One is complete. Next: Ammamma's village.",
      },
    },
    {
      n: 2,
      name: "The Village",
      native: "ఊరు",
      subtitle: "Dirt lanes and tiled roofs",
      synopsis: "Summer in Ammamma's village near Guntur. Meet her at the gate, fetch water from the well, and find your way to Tatayya by asking — left, right, straight on — in Telugu.",
      homeLines: { start: "You've just arrived in Ammamma's village.", going: "Tatayya's somewhere in the village. Ask the way.", done: "You found your way around the village. Next: the santha." },
    },
    {
      n: 3,
      name: "The Market",
      native: "సంత",
      subtitle: "Language you can hold",
      synopsis: "The weekly santha. Buy mangoes and tamarind for Ammamma, count out rupees, and learn the difference between what something is called and what it's worth.",
      homeLines: { start: "It's santha day. Ammamma's got the cloth bag.", going: "The santha's busy, and Ammamma's list isn't done.", done: "Mangoes, tamarind and change, counted in Telugu. Next: Sankranti." },
    },
    {
      n: 4,
      name: "The Festival",
      native: "సంక్రాంతి",
      subtitle: "Sankranti, from the inside",
      synopsis: "Three days of Sankranti: the Bhogi bonfire, a muggu drawn before dawn, sweets from Ammamma's kitchen and kites until the string cuts your finger.",
      homeLines: { start: "It's Bhogi morning. The bonfire's already lit.", going: "Sankranti's still going. The muggu isn't finished.", done: "Sankranti, from the inside. Next: stories under the banyan." },
    },
    {
      n: 5,
      name: "The Stories",
      native: "కథలు",
      subtitle: "Told under the banyan",
      synopsis: "Under the banyan tree at the edge of the village, by lantern light, Tatayya tells how Tenali Ramakrishna tricked a gang of thieves into watering his garden.",
      homeLines: { start: "Tatayya's under the banyan with the village kids.", going: "Tenali Rama's story isn't finished.", done: "Tenali Rama wins again. Next: the family." },
    },
    {
      n: 6,
      name: "The Family",
      native: "బంధం",
      subtitle: "Where it stops being a game",
      synopsis: "Home again. A video call to Ammamma and Tatayya in the village — and the Telugu goodbye that means you're coming back.",
      homeLines: { start: "Ammamma's calling from the village.", going: "Everyone's still on the call.", done: "వెళ్ళొస్తాను — I'll go and come back. You've finished the Telugu journey." },
    },
  ],
  highlight: { native: "నీళ్ళు కావాలా?", roman: "neellu kaavaalaa?", english: "Do you want water?", context: "The last line of Chapter One. By then, you don't need the translation." },
};

export default meta;
