import type { Language } from "../types";

/* ENGLISH · British English, from Yorkshire · A British family in America.
   The heritage here is a way of speaking: Nan's words, and what they mean to an American ear. */

const meta: Language = {
  id: "english",
  lang: "en-GB",
  speech: "en-GB",
  language: "English",
  native: "English",
  family: "A British family in America",
  variety: "British English · from Yorkshire",
  script: "latin",
  romanize: false,
  line: "A family from Yorkshire, living in America — from Nan's proper cuppa to a Christmas panto. The same language, a whole other world of words.",
  journeys: ["Tea, biscuits and the kitchen table", "Festivals through the British year", "Nursery rhymes, pantomimes and folk tales", "Other English-speaking families — Scotland, Ireland, Jamaica, Nigeria, India, Australia"],
  a: "#2a3a6a",
  b: "#b8303a",
  rank: 1,
  cover: 2,
  speakers: {
    nan: { name: "Nan", glyph: "N", tone: "elder" },
    grandad: { name: "Grandad", glyph: "G", tone: "elder" },
    mum: { name: "Mum", glyph: "M", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    // ch1 — a proper cuppa
    { id: "nan", native: "Nan", roman: "Nan", english: "grandma", group: "family", where: "the front door", ch: 1 },
    { id: "mum", native: "Mum", roman: "Mum", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "love", native: "love", roman: "love", english: "sweetie — what Nan calls everyone", group: "family", where: "every sentence Nan says", ch: 1 },
    { id: "eyup", native: "ey up", roman: "ey up", english: "hi there (Yorkshire)", group: "home", where: "the front door", ch: 1 },
    { id: "lounge", native: "lounge", roman: "lounge", english: "living room", group: "home", where: "the front room", ch: 1 },
    { id: "telly", native: "telly", roman: "telly", english: "TV", group: "home", where: "the lounge", ch: 1 },
    { id: "jumper", native: "jumper", roman: "jumper", english: "sweater", group: "home", where: "Nan's suitcase", ch: 1 },
    { id: "biscuit", native: "biscuit", roman: "biscuit", english: "cookie", group: "food", where: "Nan's suitcase", ch: 1 },
    { id: "crisps", native: "crisps", roman: "crisps", english: "potato chips", group: "food", where: "Nan's suitcase", ch: 1 },
    { id: "cuppa", native: "cuppa", roman: "cuppa", english: "a cup of tea", group: "food", where: "the kitchen", ch: 1 },
    { id: "brew", native: "brew", roman: "brew", english: "a cup of tea (not beer!)", group: "food", where: "the kitchen", ch: 1 },
    { id: "kettle", native: "kettle", roman: "kettle", english: "kettle — for tea, always on", group: "home", where: "the counter", ch: 1 },
    { id: "goonthen", native: "go on, then", roman: "go on, then", english: "yes, please (a British way of accepting)", group: "home", where: "the kitchen table", ch: 1 },
    // ch2 — the high street
    { id: "grandad", native: "Grandad", roman: "Grandad", english: "grandpa", group: "family", where: "the high street", ch: 2 },
    { id: "highstreet", native: "high street", roman: "high street", english: "main street", group: "home", where: "Nan's town", ch: 2 },
    { id: "pavement", native: "pavement", roman: "pavement", english: "sidewalk", group: "home", where: "the high street", ch: 2 },
    { id: "queue", native: "queue", roman: "queue", english: "line (of people)", group: "home", where: "every shop", ch: 2 },
    { id: "greengrocer", native: "greengrocer", roman: "greengrocer", english: "produce store", group: "home", where: "the high street", ch: 2 },
    { id: "courgette", native: "courgette", roman: "courgette", english: "zucchini", group: "food", where: "the greengrocer's", ch: 2 },
    { id: "aubergine", native: "aubergine", roman: "aubergine", english: "eggplant", group: "food", where: "the greengrocer's", ch: 2 },
    { id: "swede", native: "swede", roman: "swede", english: "rutabaga", group: "food", where: "the greengrocer's", ch: 2 },
    { id: "springonions", native: "spring onions", roman: "spring onions", english: "scallions · green onions", group: "food", where: "the greengrocer's", ch: 2 },
    { id: "quid", native: "quid", roman: "quid", english: "pounds (money, slang)", group: "home", where: "paying at the greengrocer's", ch: 2 },
    { id: "chippy", native: "chippy", roman: "chippy", english: "fish-and-chip shop", group: "food", where: "the end of the high street", ch: 2 },
    { id: "chips", native: "chips", roman: "chips", english: "French fries", group: "food", where: "the chippy", ch: 2 },
    { id: "ta", native: "ta", roman: "ta", english: "thanks", group: "home", where: "the chippy", ch: 2 },
    // ch3 — sunday roast
    { id: "roast", native: "Sunday roast", roman: "Sunday roast", english: "the big Sunday lunch", group: "food", where: "Nan's kitchen", ch: 3 },
    { id: "yorkshirepud", native: "Yorkshire pudding", roman: "Yorkshire pudding", english: "a puffy, crispy batter popover", group: "food", where: "the oven", ch: 3 },
    { id: "roasties", native: "roasties", roman: "roasties", english: "roast potatoes", group: "food", where: "the oven", ch: 3 },
    { id: "gravy", native: "gravy", roman: "gravy", english: "gravy — on everything", group: "food", where: "the gravy boat", ch: 3 },
    { id: "veg", native: "veg", roman: "veg", english: "vegetables", group: "food", where: "the stove", ch: 3 },
    { id: "tin", native: "tin", roman: "tin", english: "baking pan · can", group: "home", where: "the oven", ch: 3 },
    { id: "hob", native: "hob", roman: "hob", english: "stovetop", group: "home", where: "the kitchen", ch: 3 },
    { id: "pudding", native: "pudding", roman: "pudding", english: "dessert (any dessert!)", group: "food", where: "after the roast", ch: 3 },
    { id: "custard", native: "custard", roman: "custard", english: "a warm vanilla sauce for pudding", group: "food", where: "the jug", ch: 3 },
    { id: "stuffed", native: "stuffed", roman: "stuffed", english: "completely full", group: "home", where: "after the roast", ch: 3 },
    // ch4 — bonfire night
    { id: "bonfirenight", native: "Bonfire Night", roman: "Bonfire Night", english: "November 5th — fireworks night", group: "home", where: "the park", ch: 4 },
    { id: "bonfire", native: "bonfire", roman: "bonfire", english: "a big outdoor fire", group: "home", where: "the park", ch: 4 },
    { id: "fireworks", native: "fireworks", roman: "fireworks", english: "fireworks", group: "home", where: "the sky", ch: 4 },
    { id: "sparkler", native: "sparkler", roman: "sparkler", english: "sparkler", group: "home", where: "Grandad's pocket", ch: 4 },
    { id: "wellies", native: "wellies", roman: "wellies", english: "rain boots", group: "home", where: "the back door", ch: 4 },
    { id: "woollyhat", native: "woolly hat", roman: "woolly hat", english: "beanie", group: "home", where: "the coat hooks", ch: 4 },
    { id: "parkin", native: "parkin", roman: "parkin", english: "sticky Yorkshire ginger cake", group: "food", where: "Nan's tin", ch: 4 },
    { id: "toffeeapple", native: "toffee apple", roman: "toffee apple", english: "candy apple", group: "food", where: "the stall", ch: 4 },
    { id: "remember", native: "remember, remember", roman: "remember, remember", english: "the start of the Bonfire Night rhyme", group: "home", where: "Grandad's rhyme", ch: 4 },
    // ch5 — the panto
    { id: "panto", native: "panto", roman: "panto", english: "pantomime — a silly Christmas musical play", group: "home", where: "the town theatre", ch: 5 },
    { id: "interval", native: "interval", roman: "interval", english: "intermission", group: "home", where: "halfway through", ch: 5 },
    { id: "stalls", native: "the stalls", roman: "the stalls", english: "the downstairs seats", group: "home", where: "the theatre", ch: 5 },
    { id: "dame", native: "the Dame", roman: "the Dame", english: "the panto's funny lady — always played by a man", group: "home", where: "the stage", ch: 5 },
    { id: "lordmayor", native: "Lord Mayor", roman: "Lord Mayor", english: "the mayor of the City of London", group: "home", where: "the story", ch: 5 },
    { id: "bells", native: "bells", roman: "bells", english: "church bells", group: "home", where: "the story", ch: 5 },
    { id: "behindyou", native: "he's behind you!", roman: "he's behind you!", english: "what the whole audience shouts", group: "home", where: "the panto", ch: 5 },
    { id: "ohyesheis", native: "oh yes he is!", roman: "oh yes he is!", english: "the panto answer to “oh no he isn't!”", group: "home", where: "the panto", ch: 5 },
    // ch6 — the family
    { id: "souvenir", native: "keepsake", roman: "keepsake", english: "something to remember by", group: "home", where: "your suitcase", ch: 6 },
    { id: "auntie", native: "auntie", roman: "auntie", english: "aunt", group: "family", where: "the video call", ch: 6 },
    { id: "uncle", native: "uncle", roman: "uncle", english: "uncle", group: "family", where: "the video call", ch: 6 },
    { id: "ourkid", native: "our kid", roman: "our kid", english: "my brother or sister (Northern English)", group: "family", where: "the video call", ch: 6 },
    { id: "cousin", native: "cousin", roman: "cousin", english: "cousin", group: "family", where: "the video call", ch: 6 },
    { id: "missyou", native: "miss you loads", roman: "miss you loads", english: "miss you a lot", group: "family", where: "saying goodbye", ch: 6 },
    { id: "tara", native: "ta-ra", roman: "ta-ra", english: "bye! (Yorkshire)", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    tea: { title: "A proper cuppa", native: "a brew", note: "Tea with milk, made in a pot or a mug, several times a day. In Yorkshire it's “a brew.” Offering one is how you say hello, sorry, well done and I'm here." },
    biscuits: { title: "Dunking biscuits", native: "dunking", note: "Dipping a biscuit into your tea. Every British family has a ranking of which biscuits dunk best, and every family is sure they're right." },
    love: { title: "“Love”", native: "love", note: "In Yorkshire, everyone is “love” — the bus driver, the shopkeeper, the stranger asking the time. It means you're welcome here." },
    queue: { title: "The queue", native: "queuing", note: "Lining up, patiently and in order. Pushing in is the worst thing you can do in Britain. Possibly worse than anything in the law." },
    highstreet: { title: "The high street", native: "the high street", note: "The main shopping street of every British town: the chemist, the greengrocer, the charity shop, the chippy — and somebody you know in every one." },
    chippy: { title: "Fish and chips", native: "the chippy", note: "Battered fish and thick chips, salt and vinegar, wrapped in paper. Friday night tea in half of Britain." },
    sundayroast: { title: "Sunday roast", native: "Sunday dinner", note: "Roast meat, roast potatoes, vegetables, gravy and — in the north — Yorkshire puddings. The whole family, every Sunday, at about one o'clock." },
    yorkshirepud: { title: "Yorkshire puddings", native: "Yorkshire puds", note: "Batter poured into smoking-hot fat, puffing up golden and hollow. The golden rule: never open the oven door." },
    pudding: { title: "Pudding means dessert", native: "pudding", note: "In Britain, “pudding” is any dessert at all — cake, crumble, trifle, ice cream. “What's for pudding?” is the most important question of Sunday." },
    tea3: { title: "Dinner, tea and supper", native: "tea", note: "In the north of England, lunch is often “dinner” and the evening meal is “tea.” Which can make “What's for tea?” very confusing." },
    bonfirenight: { title: "Bonfire Night", native: "Guy Fawkes Night", note: "Every November 5th since 1605, Britain lights bonfires and fireworks to remember the night a plot to blow up Parliament was stopped." },
    parkin: { title: "Parkin", native: "parkin", note: "A dark, sticky ginger cake made with oats and treacle. It's traditional on Bonfire Night in Yorkshire — and it gets better if you leave it a week." },
    panto: { title: "Panto", native: "pantomime", note: "A silly, musical Christmas play for families — a fairy tale with jokes, a Dame played by a man, and an audience that shouts back." },
    whittington: { title: "Dick Whittington", native: "Richard Whittington", note: "A real man — Richard Whittington was Lord Mayor of London four times in the 1400s. The story of the cat came later, but everyone prefers it." },
  },
  memoryNotes: {
    eyup: { title: "Greeted Nan", note: "“Ey up, love!” — and a hug that smelled of Yorkshire." },
    kitchen: { title: "Found the tea things", note: "Kettle, teapot, milk, biscuits — by ear." },
    brew: { title: "Made a proper brew", note: "Boil, warm the pot, tea in, brew, milk." },
    goonthen: { title: "“Go on, then!”", note: "Nan asked if you fancied a brew. You said yes the British way." },
    veg: { title: "Shopped at the greengrocer's", note: "Courgette, aubergine, swede, spring onions." },
    quid: { title: "Paid in quid", note: "Two, three, five, ten — pounds, not dollars." },
    ta: { title: "“That's everything, ta!”", note: "The chippy man asked if you wanted anything else." },
    table: { title: "Laid the table for Sunday dinner", note: "Gravy, roasties, veg, Yorkshire puds." },
    puds: { title: "Made Yorkshire puddings", note: "Hot tin, batter, oven — and never open the door." },
    pudding: { title: "“Me, please!”", note: "Nan asked who was for pudding. You knew it meant dessert." },
    wrapped: { title: "Wrapped up for Bonfire Night", note: "Wellies, woolly hat, scarf, gloves." },
    parkin: { title: "Shared out the parkin", note: "Slices for everyone round the bonfire." },
    remember: { title: "“…the fifth of November!”", note: "Grandad started the rhyme. You finished it." },
    test: { title: "Beat Ellie's word test", note: "In the interval, with an ice cream." },
    story: { title: "Dick Whittington", note: "Watched at the Christmas panto, with the whole family shouting." },
    ohyes: { title: "“Oh yes he is!”", note: "The Dame said he wasn't. You knew better." },
    keepsakes: { title: "Unpacked Yorkshire", note: "Tea bags, a woolly hat, a panto programme." },
    call: { title: "Named everyone on the call", note: "Auntie, Uncle, our kid, your cousin." },
    retold: { title: "Told your autumn, British-style", note: "Brew, chippy, bonfire, panto — in order." },
    tara: { title: "“Ta-ra!”", note: "Not goodbye. Ta-ra, love — see you soon." },
  },
  chapters: [
    {
      n: 1,
      name: "A Proper Cuppa",
      native: "A Proper Cuppa",
      subtitle: "Nan arrives from Yorkshire",
      synopsis: "Nan has flown in from Yorkshire with a suitcase full of tea bags, biscuits and jumpers. She speaks English — just not quite the English you know. Learn her words, make her a proper brew, and answer her the Yorkshire way.",
      homeLines: {
        start: "Nan's just arrived from Yorkshire. She's at the front door.",
        going: "The kettle's on. Nan's waiting for her brew.",
        done: "Nan has her cuppa and you have a biscuit. Next: Nan's high street.",
      },
    },
    {
      n: 2,
      name: "The High Street",
      native: "The High Street",
      subtitle: "Queues, quid and the chippy",
      synopsis: "Autumn in Nan's Yorkshire market town. Walk down the high street with Grandad, shop at the greengrocer's where nothing is called what you'd call it, pay in quid — and join the queue at the chippy.",
      homeLines: { start: "Grandad's got his flat cap on. Shopping day.", going: "The greengrocer's queue is out the door.", done: "Chips in paper, walking home. Next: Sunday roast." },
    },
    {
      n: 3,
      name: "Sunday Roast",
      native: "Sunday Roast",
      subtitle: "Never open the oven door",
      synopsis: "Sunday dinner at Nan's: lay the table, make Yorkshire puddings from scratch — and find out what the British mean by “pudding.”",
      homeLines: { start: "The roast is in. The Yorkshire puds are not.", going: "Don't open the oven door.", done: "Stuffed. Completely stuffed. Next: Bonfire Night." },
    },
    {
      n: 4,
      name: "Bonfire Night",
      native: "Bonfire Night",
      subtitle: "Remember, remember",
      synopsis: "November 5th: wrap up warm, share Nan's sticky parkin round the bonfire, write your name with a sparkler — and finish Grandad's rhyme.",
      homeLines: { start: "Wellies on. The bonfire's lit.", going: "The fireworks haven't started yet.", done: "The sky's full of fireworks. Next: the panto." },
    },
    {
      n: 5,
      name: "The Panto",
      native: "The Panto",
      subtitle: "He's behind you!",
      synopsis: "A Christmas pantomime at the town theatre: Dick Whittington and his cat, a Dame in a ridiculous dress, and an audience that is absolutely expected to shout back.",
      homeLines: { start: "The panto starts at seven. Grandad has the tickets.", going: "It's the interval. Ice cream time.", done: "Oh yes it was. Next: the family." },
    },
    {
      n: 6,
      name: "The Family",
      native: "The Family",
      subtitle: "Calling Yorkshire",
      synopsis: "Home in America again. A video call to Yorkshire — Auntie, Uncle, cousins and “our kid.” Tell your whole autumn the British way, and say goodbye like Nan does.",
      homeLines: { start: "Yorkshire is calling.", going: "Everyone's still on the call.", done: "Ta-ra, love! You've finished the English journey." },
    },
  ],
  highlight: { native: "Oh yes he is!", roman: "", english: "(the panto reply)", context: "The Dame swears the villain isn't behind her. Four hundred people — and you — know better." },
};

export default meta;
