import type { Language } from "../types";

/* RUSSIAN · Cyrillic · A Russian-speaking family from St. Petersburg. Six chapters, from Babushka's blini to a call across the sea. */

const meta: Language = {
  id: "russian",
  lang: "ru",
  speech: "ru",
  language: "Russian",
  native: "Русский",
  family: "A Russian-speaking family from St. Petersburg",
  variety: "Russian · Cyrillic script",
  script: "ru",
  romanize: true,
  line: "A family from St. Petersburg, from Babushka's blini to New Year under the yolka. One Russian-speaking world of many.",
  journeys: ["The kitchen and the dacha", "Holidays through the year", "Folk tales and poems", "Other Russian-speaking families, across many countries"],
  a: "#2d4a8a",
  b: "#b8453a",
  rank: 9,
  cover: 4,
  speakers: {
    babushka: { name: "Babushka", glyph: "Б", tone: "elder" },
    dedushka: { name: "Dedushka", glyph: "Д", tone: "elder" },
    mama: { name: "Mama", glyph: "М", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    // ch1 — блины
    { id: "babushka", native: "бабушка", roman: "babushka", english: "grandma", group: "family", where: "the front door", ch: 1 },
    { id: "mama", native: "мама", roman: "mama", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "papa", native: "папа", roman: "papa", english: "dad", group: "family", where: "the airport run", ch: 1 },
    { id: "semya", native: "семья", roman: "sem'ya", english: "family", group: "family", where: "the photos in the hall", ch: 1 },
    { id: "dom", native: "дом", roman: "dom", english: "home · house", group: "home", where: "the front door", ch: 1 },
    { id: "privet", native: "привет", roman: "privet", english: "hi", group: "home", where: "the front door", ch: 1 },
    { id: "chemodan", native: "чемодан", roman: "chemodan", english: "suitcase", group: "home", where: "Babushka's luggage", ch: 1 },
    { id: "varenye", native: "варенье", roman: "varen'ye", english: "jam", group: "food", where: "Babushka's suitcase", ch: 1 },
    { id: "muka", native: "мука", roman: "muka", english: "flour", group: "food", where: "the kitchen cupboard", ch: 1 },
    { id: "yaytsa", native: "яйца", roman: "yaytsa", english: "eggs", group: "food", where: "the fridge", ch: 1 },
    { id: "moloko", native: "молоко", roman: "moloko", english: "milk", group: "food", where: "the fridge", ch: 1 },
    { id: "sakhar", native: "сахар", roman: "sakhar", english: "sugar", group: "food", where: "the kitchen cupboard", ch: 1 },
    { id: "skovoroda", native: "сковорода", roman: "skovoroda", english: "frying pan", group: "home", where: "the stove", ch: 1 },
    { id: "blin", native: "блин", roman: "blin", english: "blin — a thin pancake", group: "food", where: "Babushka's pan", ch: 1 },
    { id: "smetana", native: "сметана", roman: "smetana", english: "sour cream", group: "food", where: "the table", ch: 1 },
    { id: "pozhaluysta", native: "пожалуйста", roman: "pozhaluysta", english: "please", group: "home", where: "the kitchen table", ch: 1 },
    // ch2 — дача
    { id: "dedushka", native: "дедушка", roman: "dedushka", english: "grandpa", group: "family", where: "the dacha garden", ch: 2 },
    { id: "dacha", native: "дача", roman: "dacha", english: "dacha — a summer cottage", group: "home", where: "outside St. Petersburg", ch: 2 },
    { id: "sad", native: "сад", roman: "sad", english: "garden", group: "home", where: "the dacha", ch: 2 },
    { id: "klubnika", native: "клубника", roman: "klubnika", english: "strawberries", group: "food", where: "the garden beds", ch: 2 },
    { id: "malina", native: "малина", roman: "malina", english: "raspberries", group: "food", where: "the garden beds", ch: 2 },
    { id: "smorodina", native: "смородина", roman: "smorodina", english: "currants", group: "food", where: "the garden beds", ch: 2 },
    { id: "ogurtsy", native: "огурцы", roman: "ogurtsy", english: "cucumbers", group: "food", where: "the greenhouse", ch: 2 },
    { id: "banka", native: "банка", roman: "banka", english: "jar", group: "home", where: "the veranda", ch: 2 },
    { id: "odin", native: "один", roman: "odin", english: "one", group: "home", where: "the pickling jars", ch: 2 },
    { id: "dva", native: "два", roman: "dva", english: "two", group: "home", where: "the pickling jars", ch: 2 },
    { id: "tri", native: "три", roman: "tri", english: "three", group: "home", where: "the pickling jars", ch: 2 },
    { id: "chetyre", native: "четыре", roman: "chetyre", english: "four", group: "home", where: "the pickling jars", ch: 2 },
    { id: "griby", native: "грибы", roman: "griby", english: "mushrooms", group: "food", where: "the forest behind the dacha", ch: 2 },
    { id: "khochu", native: "хочу", roman: "khochu", english: "I want (to)", group: "home", where: "the dacha gate", ch: 2 },
    // ch3 — рынок
    { id: "rynok", native: "рынок", roman: "rynok", english: "market", group: "home", where: "the covered market", ch: 3 },
    { id: "myod", native: "мёд", roman: "myod", english: "honey", group: "food", where: "the honey stall", ch: 3 },
    { id: "tvorog", native: "творог", roman: "tvorog", english: "tvorog — farmer's cheese", group: "food", where: "the dairy counter", ch: 3 },
    { id: "yabloki", native: "яблоки", roman: "yabloki", english: "apples", group: "food", where: "the dairy counter", ch: 3 },
    { id: "kartoshka", native: "картошка", roman: "kartoshka", english: "potatoes", group: "food", where: "the dairy counter", ch: 3 },
    { id: "rubl", native: "рубль", roman: "rubl'", english: "rouble", group: "home", where: "the honey row", ch: 3 },
    { id: "pyat", native: "пять", roman: "pyat'", english: "five", group: "home", where: "Tyotya Galya's stall", ch: 3 },
    { id: "desyat", native: "десять", roman: "desyat'", english: "ten", group: "home", where: "Tyotya Galya's stall", ch: 3 },
    { id: "skolko", native: "сколько стоит?", roman: "skol'ko stoit?", english: "how much is it?", group: "home", where: "the honey stall", ch: 3 },
    { id: "dorogo", native: "дорого", roman: "dorogo", english: "expensive", group: "home", where: "the honey stall", ch: 3 },
    { id: "spasibo", native: "спасибо", roman: "spasibo", english: "thank you", group: "home", where: "the honey stall", ch: 3 },
    // ch4 — новый год
    { id: "novyygod", native: "Новый год", roman: "Novyy god", english: "New Year", group: "home", where: "December 31st", ch: 4 },
    { id: "yolka", native: "ёлка", roman: "yolka", english: "New Year tree", group: "home", where: "the living room", ch: 4 },
    { id: "zvezda", native: "звезда", roman: "zvezda", english: "star", group: "home", where: "the top of the yolka", ch: 4 },
    { id: "shariki", native: "шарики", roman: "shariki", english: "baubles", group: "home", where: "the decoration box", ch: 4 },
    { id: "girlyanda", native: "гирлянда", roman: "girlyanda", english: "string of lights", group: "home", where: "the decoration box", ch: 4 },
    { id: "mandariny", native: "мандарины", roman: "mandariny", english: "tangerines", group: "food", where: "the bowl on the table", ch: 4 },
    { id: "olivye", native: "оливье", roman: "olivye", english: "Olivier salad", group: "food", where: "the New Year table", ch: 4 },
    { id: "kuranty", native: "куранты", roman: "kuranty", english: "the midnight chimes", group: "home", where: "the television", ch: 4 },
    { id: "zhelanie", native: "желание", roman: "zhelaniye", english: "a wish", group: "home", where: "a scrap of paper at midnight", ch: 4 },
    { id: "podarki", native: "подарки", roman: "podarki", english: "presents", group: "home", where: "under the yolka", ch: 4 },
    { id: "dedmoroz", native: "Дед Мороз", roman: "Ded Moroz", english: "Grandfather Frost", group: "home", where: "the front door at 10 p.m.", ch: 4 },
    // ch5 — репка
    { id: "skazka", native: "сказка", roman: "skazka", english: "fairy tale", group: "home", where: "Dedushka's armchair", ch: 5 },
    { id: "repka", native: "репка", roman: "repka", english: "turnip", group: "food", where: "Dedushka's tale", ch: 5 },
    { id: "bolshaya", native: "большая", roman: "bol'shaya", english: "big", group: "home", where: "Dedushka's tale", ch: 5 },
    { id: "tyanut", native: "тянут", roman: "tyanut", english: "(they) pull", group: "home", where: "Dedushka's tale", ch: 5 },
    { id: "vnuchka", native: "внучка", roman: "vnuchka", english: "granddaughter", group: "family", where: "Dedushka's tale", ch: 5 },
    { id: "sobaka", native: "собака", roman: "sobaka", english: "dog", group: "home", where: "Dedushka's tale", ch: 5 },
    { id: "koshka", native: "кошка", roman: "koshka", english: "cat", group: "home", where: "Dedushka's tale", ch: 5 },
    { id: "myshka", native: "мышка", roman: "myshka", english: "little mouse", group: "home", where: "Dedushka's tale", ch: 5 },
    { id: "vmeste", native: "вместе", roman: "vmeste", english: "together", group: "home", where: "Dedushka's tale", ch: 5 },
    { id: "sneg", native: "снег", roman: "sneg", english: "snow", group: "home", where: "the window", ch: 5 },
    // ch6 — семья
    { id: "pamyat", native: "на память", roman: "na pamyat'", english: "as a keepsake (lit. “for memory”)", group: "home", where: "your suitcase", ch: 6 },
    { id: "dyadya", native: "дядя", roman: "dyadya", english: "uncle", group: "family", where: "the video call", ch: 6 },
    { id: "tyotya", native: "тётя", roman: "tyotya", english: "aunt", group: "family", where: "the video call", ch: 6 },
    { id: "brat", native: "брат", roman: "brat", english: "brother · boy cousin", group: "family", where: "the video call", ch: 6 },
    { id: "sestra", native: "сестра", roman: "sestra", english: "sister · girl cousin", group: "family", where: "the video call", ch: 6 },
    { id: "skoro", native: "скоро", roman: "skoro", english: "soon", group: "home", where: "saying goodbye", ch: 6 },
    { id: "skuchayu", native: "скучаю", roman: "skuchayu", english: "I miss (you)", group: "family", where: "saying goodbye", ch: 6 },
    { id: "dovstrechi", native: "до встречи", roman: "do vstrechi", english: "see you soon — “until we meet”", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    matryoshka: { title: "Matryoshka", native: "матрёшка", note: "Painted wooden dolls, each one hiding a smaller one inside. The smallest — the size of a fingernail — doesn't open." },
    chai: { title: "Tea from a glass", native: "подстаканник", note: "Tea served in a glass inside an ornate metal holder — the way it's still served on Russian trains. With jam instead of sugar, by the spoonful." },
    pervyblin: { title: "“Первый блин комом”", native: "первый блин комом", note: "“The first blin is always a lump.” Said about any first try that goes wrong. The first blin really does always stick." },
    maslenitsa: { title: "Maslenitsa", native: "Масленица", note: "Butter Week, at the end of winter: a week of blini, each one round and golden like the sun coming back." },
    dacha: { title: "The dacha", native: "дача", note: "A wooden summer house outside the city, with a vegetable garden. Every weekend from May to September, half of St. Petersburg leaves for theirs." },
    pickling: { title: "Pickling", native: "соленья", note: "Cucumbers, tomatoes, mushrooms — packed into jars with dill and garlic in August, eaten all winter. Every babushka's recipe is a state secret." },
    griby: { title: "Mushroom hunting", native: "за грибами", note: "Going “for mushrooms” with a basket and a knife is a national sport. Everybody has a secret spot. Nobody tells." },
    kuznechny: { title: "The covered market", native: "Кузнечный рынок", note: "St. Petersburg's old covered market: honey from ten regions, pickles by the barrel, and sellers who insist you taste before you buy." },
    tasting: { title: "Попробуйте!", native: "попробуйте", note: "“Try it!” At the market, you taste the honey, the tvorog, the pickles — before anyone expects you to pay." },
    novyygod: { title: "Новый год", native: "Новый год", note: "New Year's Eve is the biggest holiday of the year: the tree, the presents, the table and the whole family, until long after midnight." },
    dedmoroz: { title: "Ded Moroz and Snegurochka", native: "Дед Мороз и Снегурочка", note: "Grandfather Frost, in a long blue or red coat with a staff, and his granddaughter, the Snow Maiden. They bring the presents on New Year's Eve." },
    kuranty: { title: "The chimes", native: "куранты", note: "At midnight, everyone watches the Kremlin clock on television strike twelve. Some people write a wish on paper, burn it, and drop the ashes into their glass before the twelfth chime." },
    olivye: { title: "Olivier salad", native: "салат оливье", note: "Potatoes, peas, carrots, pickles, eggs and mayonnaise. Every New Year table has a bowl of it the size of a steering wheel." },
    repka: { title: "Репка", native: "Репка", note: "“The Turnip” — one of the first folk tales every Russian child hears. It builds, one helper at a time, until the smallest one makes the difference." },
    whitenights: { title: "White nights", native: "белые ночи", note: "In June, St. Petersburg is so far north that the sky never gets fully dark. The bridges open at night and the whole city stays up." },
  },
  memoryNotes: {
    privet: { title: "Greeted Babushka", note: "Three kisses, one on each cheek and one more." },
    batter: { title: "Helped Babushka with the batter", note: "Мука, яйца, молоко, сахар — passed by ear." },
    blini: { title: "Made blini", note: "The first one was a lump. The second was perfect." },
    pozhaluysta: { title: "“Да, пожалуйста!”", note: "Babushka offered another blin. You said yes — in Russian." },
    berries: { title: "Picked berries at the dacha", note: "Клубника, малина, смородина, огурцы." },
    jars: { title: "Filled the pickling jars", note: "Один, два, три, четыре — Dedushka's recipe." },
    khochu: { title: "“Хочу!”", note: "Dedushka asked if you wanted to go mushroom hunting." },
    paid: { title: "Counted at the market", note: "Два, три, пять, десять — apples into the bag." },
    haggle: { title: "Watched Babushka bargain", note: "The honey was “дорого.” Then it wasn't." },
    spasibo: { title: "“Нет, спасибо!”", note: "The honey seller asked if you wanted anything else." },
    yolka: { title: "Decorated the yolka", note: "Звезда, шарики, гирлянда, мандарины." },
    evening: { title: "New Year's Eve, in order", note: "Tree, salad, chimes, wish, presents." },
    snovym: { title: "“С Новым годом!”", note: "Shouted on the twelfth chime, with everyone." },
    test: { title: "Beat Sasha's word test", note: "By the window, in the snow." },
    repka: { title: "Репка", note: "Dedushka's tale — and it took all of them." },
    myshka: { title: "“Мышка!”", note: "Dedushka asked who made the difference. The smallest one." },
    keepsakes: { title: "Unpacked St. Petersburg", note: "A matryoshka, a jar of Babushka's jam, a paper snowflake." },
    call: { title: "Named everyone on the call", note: "Дядя, тётя, брат, сестра." },
    retold: { title: "Told your year in Russian", note: "Dacha, market, yolka, repka — in order." },
    dovstrechi: { title: "“До встречи!”", note: "Not goodbye. Until we meet again." },
  },
  chapters: [
    {
      n: 1,
      name: "Blini",
      native: "Блины",
      subtitle: "Babushka arrives",
      synopsis: "Babushka has flown in from St. Petersburg with jam, a matryoshka and very firm opinions about pancakes. Greet her properly, help with the batter, survive the first blin — and ask for another.",
      homeLines: {
        start: "Babushka's just arrived from St. Petersburg. She's in the front hall.",
        going: "The batter's ready. Babushka's by the stove.",
        done: "The blini are gone and the tea is poured. Next: the dacha.",
      },
    },
    {
      n: 2,
      name: "The Dacha",
      native: "Дача",
      subtitle: "Berries, jars and a forest",
      synopsis: "Summer at the family dacha outside St. Petersburg. Pick berries with Dedushka, count cucumbers into the pickling jars — and get invited into the forest for mushrooms.",
      homeLines: { start: "Dedushka's in the garden with a basket.", going: "The pickling jars are still half empty.", done: "Jars sealed, berries picked. Next: the market." },
    },
    {
      n: 3,
      name: "The Market",
      native: "Рынок",
      subtitle: "Taste before you buy",
      synopsis: "Babushka's covered market in the city: honey from ten regions, tvorog, apples, and sellers who make you taste everything. Count apples into the bag and watch Babushka bargain for the good honey.",
      homeLines: { start: "Babushka's bag is by the door. Market day.", going: "The market's busy, and Babushka still has a list.", done: "Bag full, honey won. Next: New Year." },
    },
    {
      n: 4,
      name: "New Year",
      native: "Новый год",
      subtitle: "The yolka and the chimes",
      synopsis: "The biggest night of the year: decorate the yolka, set the table, wait for Ded Moroz — and shout the right thing on the twelfth chime.",
      homeLines: { start: "The yolka's up, but bare.", going: "The chimes haven't struck yet.", done: "С Новым годом! Next: Dedushka's tale." },
    },
    {
      n: 5,
      name: "The Turnip",
      native: "Репка",
      subtitle: "A tale for a snowy night",
      synopsis: "Snow outside, tea inside, and Dedushka tells the oldest story in the family: a turnip so big it takes everybody to pull it out — right down to the smallest mouse.",
      homeLines: { start: "Dedushka's in his armchair by the window.", going: "The turnip's still stuck.", done: "Out it came — thanks to the mouse. Next: the family." },
    },
    {
      n: 6,
      name: "Family",
      native: "Семья",
      subtitle: "Calling St. Petersburg",
      synopsis: "Home again. A video call to St. Petersburg: an uncle, an aunt and cousins who are also, in Russian, your brother and sister. Tell your whole year in Russian — and say goodbye the way you'll see each other again.",
      homeLines: { start: "St. Petersburg is calling.", going: "Everyone's still on the call.", done: "До встречи! You've finished the Russian journey." },
    },
  ],
  highlight: { native: "С Новым годом!", roman: "S Novym godom!", english: "Happy New Year!", context: "Shouted on the twelfth chime of the Kremlin clock, with the whole family — and you with them." },
};

export default meta;
