import type { Language } from "../types";

/* BENGALI · Bengali script · A Bangladeshi family in New York. Six chapters, from Nanu's winter pitha to Pohela Boishakh. */

const meta: Language = {
  id: "bengali",
  lang: "bn-BD",
  speech: "bn",
  language: "Bengali",
  native: "বাংলা",
  family: "A Bangladeshi family in New York",
  variety: "Bengali · as spoken in Bangladesh",
  script: "bn",
  romanize: true,
  line: "A Bangladeshi family in Queens, from Nanu's winter pitha to Pohela Boishakh in Dhaka. One Bengali-speaking world of many.",
  journeys: ["Rivers, rice and the village", "Festivals through the Bengali year", "Stories, rhymes and songs", "Other Bengali-speaking families — Kolkata and West Bengal, London, the Gulf"],
  a: "#1f6a4a",
  b: "#c8302a",
  rank: 7,
  speakers: {
    nanu: { name: "Nanu", glyph: "না", tone: "elder" },
    nana: { name: "Nana", glyph: "না", tone: "elder" },
    ammu: { name: "Ammu", glyph: "আ", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    // ch1 — পিঠা
    { id: "nanu", native: "নানু", roman: "nanu", english: "grandma (mom's mother)", group: "family", where: "the front door", ch: 1 },
    { id: "ammu", native: "আম্মু", roman: "ammu", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "abbu", native: "আব্বু", roman: "abbu", english: "dad", group: "family", where: "the airport run", ch: 1 },
    { id: "poribar", native: "পরিবার", roman: "poribar", english: "family", group: "family", where: "the photos in the hall", ch: 1 },
    { id: "bari", native: "বাড়ি", roman: "bari", english: "home · house", group: "home", where: "the front door", ch: 1 },
    { id: "salam", native: "সালাম", roman: "salam", english: "salam — a respectful greeting", group: "home", where: "the front door", ch: 1 },
    { id: "suitcase", native: "সুটকেস", roman: "suitkes", english: "suitcase", group: "home", where: "Nanu's luggage", ch: 1 },
    { id: "chalergura", native: "চালের গুঁড়া", roman: "chaler gunra", english: "rice flour", group: "food", where: "Nanu's suitcase", ch: 1 },
    { id: "gur", native: "গুড়", roman: "gur", english: "jaggery — palm sugar", group: "food", where: "Nanu's suitcase", ch: 1 },
    { id: "narkel", native: "নারকেল", roman: "narkel", english: "coconut", group: "food", where: "the kitchen counter", ch: 1 },
    { id: "pani", native: "পানি", roman: "pani", english: "water", group: "food", where: "the kitchen tap", ch: 1 },
    { id: "lobon", native: "লবণ", roman: "lobon", english: "salt", group: "food", where: "the spice shelf", ch: 1 },
    { id: "pitha", native: "পিঠা", roman: "pitha", english: "pitha — rice cake", group: "food", where: "Nanu's steamer", ch: 1 },
    { id: "bhap", native: "ভাপ", roman: "bhap", english: "steam", group: "home", where: "the pot on the stove", ch: 1 },
    { id: "cha", native: "চা", roman: "cha", english: "tea", group: "food", where: "the kitchen", ch: 1 },
    { id: "haan", native: "হ্যাঁ", roman: "hyan", english: "yes", group: "home", where: "the kitchen table", ch: 1 },
    // ch2 — গ্রাম
    { id: "nana", native: "নানা", roman: "nana", english: "grandpa (mom's father)", group: "family", where: "the village", ch: 2 },
    { id: "gram", native: "গ্রাম", roman: "gram", english: "village", group: "home", where: "Nanu's village", ch: 2 },
    { id: "nodi", native: "নদী", roman: "nodi", english: "river", group: "home", where: "the edge of the village", ch: 2 },
    { id: "nouka", native: "নৌকা", roman: "nouka", english: "boat", group: "home", where: "the river bank", ch: 2 },
    { id: "majhi", native: "মাঝি", roman: "majhi", english: "boatman", group: "home", where: "the river bank", ch: 2 },
    { id: "pukur", native: "পুকুর", roman: "pukur", english: "pond", group: "home", where: "behind the house", ch: 2 },
    { id: "mach", native: "মাছ", roman: "mach", english: "fish", group: "food", where: "the pond", ch: 2 },
    { id: "jal", native: "জাল", roman: "jal", english: "net", group: "home", where: "the veranda", ch: 2 },
    { id: "borshi", native: "বড়শি", roman: "borshi", english: "fishing rod", group: "home", where: "the veranda", ch: 2 },
    { id: "balti", native: "বালতি", roman: "balti", english: "bucket", group: "home", where: "the veranda", ch: 2 },
    { id: "chhata", native: "ছাতা", roman: "chhata", english: "umbrella", group: "home", where: "the veranda", ch: 2 },
    { id: "ek", native: "এক", roman: "ek", english: "one", group: "home", where: "the pond", ch: 2 },
    { id: "dui", native: "দুই", roman: "dui", english: "two", group: "home", where: "the pond", ch: 2 },
    { id: "tin", native: "তিন", roman: "tin", english: "three", group: "home", where: "the pond", ch: 2 },
    { id: "char", native: "চার", roman: "char", english: "four", group: "home", where: "the pond", ch: 2 },
    { id: "opar", native: "ওপার", roman: "opar", english: "the other side (of the river)", group: "home", where: "the ferry", ch: 2 },
    { id: "brishti", native: "বৃষ্টি", roman: "brishti", english: "rain", group: "home", where: "the April sky", ch: 2 },
    // ch3 — বাজার
    { id: "bazar", native: "বাজার", roman: "bajar", english: "market · bazaar", group: "home", where: "the town", ch: 3 },
    { id: "ilish", native: "ইলিশ", roman: "ilish", english: "hilsa — Bangladesh's national fish", group: "food", where: "the fish market", ch: 3 },
    { id: "alu", native: "আলু", roman: "alu", english: "potato", group: "food", where: "the vegetable stall", ch: 3 },
    { id: "begun", native: "বেগুন", roman: "begun", english: "eggplant", group: "food", where: "the vegetable stall", ch: 3 },
    { id: "lau", native: "লাউ", roman: "lau", english: "bottle gourd", group: "food", where: "the vegetable stall", ch: 3 },
    { id: "morich", native: "কাঁচা মরিচ", roman: "kancha morich", english: "green chillies", group: "food", where: "the vegetable stall", ch: 3 },
    { id: "taka", native: "টাকা", roman: "taka", english: "taka (Bangladesh's money)", group: "home", where: "paying in the bazaar", ch: 3 },
    { id: "panch", native: "পাঁচ", roman: "panch", english: "five", group: "home", where: "paying in the bazaar", ch: 3 },
    { id: "dosh", native: "দশ", roman: "dosh", english: "ten", group: "home", where: "paying in the bazaar", ch: 3 },
    { id: "damkoto", native: "দাম কত?", roman: "dam koto?", english: "how much?", group: "home", where: "the fish market", ch: 3 },
    { id: "beshi", native: "অনেক বেশি", roman: "onek beshi", english: "too much", group: "home", where: "the fish market", ch: 3 },
    { id: "dhonnobad", native: "ধন্যবাদ", roman: "dhonnobad", english: "thank you", group: "home", where: "the fish market", ch: 3 },
    // ch4 — পহেলা বৈশাখ
    { id: "pohela", native: "পহেলা বৈশাখ", roman: "pohela boishakh", english: "Pohela Boishakh — Bengali New Year", group: "home", where: "April 14th", ch: 4 },
    { id: "shubho", native: "শুভ নববর্ষ", roman: "shubho noboborsho", english: "Happy New Year", group: "home", where: "everybody, all day", ch: 4 },
    { id: "mela", native: "মেলা", roman: "mela", english: "fair", group: "home", where: "the field by the school", ch: 4 },
    { id: "alpona", native: "আলপনা", roman: "alpona", english: "alpona — painted floor patterns", group: "home", where: "the courtyard", ch: 4 },
    { id: "lal", native: "লাল", roman: "lal", english: "red", group: "home", where: "the paint pots", ch: 4 },
    { id: "sada", native: "সাদা", roman: "sada", english: "white", group: "home", where: "the paint pots", ch: 4 },
    { id: "holud", native: "হলুদ", roman: "holud", english: "yellow", group: "home", where: "the paint pots", ch: 4 },
    { id: "sobuj", native: "সবুজ", roman: "sobuj", english: "green", group: "home", where: "the paint pots", ch: 4 },
    { id: "mukhosh", native: "মুখোশ", roman: "mukhosh", english: "mask", group: "home", where: "the procession", ch: 4 },
    { id: "dhol", native: "ঢোল", roman: "dhol", english: "drum", group: "home", where: "the procession", ch: 4 },
    { id: "panta", native: "পান্তা ভাত", roman: "panta bhat", english: "panta — rice soaked overnight", group: "food", where: "New Year breakfast", ch: 4 },
    { id: "mishti", native: "মিষ্টি", roman: "mishti", english: "sweets", group: "food", where: "the sweet shop", ch: 4 },
    // ch5 — টুনটুনি
    { id: "golpo", native: "গল্প", roman: "golpo", english: "story", group: "home", where: "Nanu's mat", ch: 5 },
    { id: "raat", native: "রাত", roman: "rat", english: "night", group: "home", where: "the courtyard", ch: 5 },
    { id: "chand", native: "চাঁদ", roman: "chand", english: "moon", group: "home", where: "over the courtyard", ch: 5 },
    { id: "jonaki", native: "জোনাকি", roman: "jonaki", english: "firefly", group: "home", where: "the banana trees", ch: 5 },
    { id: "tuntuni", native: "টুনটুনি", roman: "tuntuni", english: "tailorbird", group: "home", where: "Nanu's story", ch: 5 },
    { id: "biral", native: "বিড়াল", roman: "biral", english: "cat", group: "home", where: "Nanu's story", ch: 5 },
    { id: "basa", native: "বাসা", roman: "basa", english: "nest", group: "home", where: "Nanu's story", ch: 5 },
    { id: "chhana", native: "ছানা", roman: "chhana", english: "chicks", group: "home", where: "Nanu's story", ch: 5 },
    { id: "kanta", native: "কাঁটা", roman: "kanta", english: "thorn", group: "home", where: "Nanu's story", ch: 5 },
    { id: "chalak", native: "চালাক", roman: "chalak", english: "clever", group: "home", where: "after the story", ch: 5 },
    // ch6 — পরিবার
    { id: "smriti", native: "স্মৃতি", roman: "smriti", english: "memory · keepsake", group: "home", where: "your suitcase", ch: 6 },
    { id: "mama", native: "মামা", roman: "mama", english: "uncle (mom's brother)", group: "family", where: "the video call", ch: 6 },
    { id: "khala", native: "খালা", roman: "khala", english: "aunt (mom's sister)", group: "family", where: "the video call", ch: 6 },
    { id: "chacha", native: "চাচা", roman: "chacha", english: "uncle (dad's brother)", group: "family", where: "the video call", ch: 6 },
    { id: "fupu", native: "ফুপু", roman: "fupu", english: "aunt (dad's sister)", group: "family", where: "the video call", ch: 6 },
    { id: "taratari", native: "তাড়াতাড়ি", roman: "taratari", english: "soon · quickly", group: "home", where: "saying goodbye", ch: 6 },
    { id: "monepore", native: "মনে পড়বে", roman: "mone porbe", english: "(I'll) think of you · miss you", group: "family", where: "saying goodbye", ch: 6 },
    { id: "ashi", native: "আসি", roman: "ashi", english: "goodbye — “I'll come (again)”", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    salam: { title: "Salam to an elder", native: "সালাম", note: "Greeting a grandparent with “Assalamu alaikum” — or, in many families, bending to touch their feet. They answer with a blessing and, usually, food." },
    pitha: { title: "Pitha season", native: "পিঠা-পুলি", note: "Winter in Bangladesh is pitha season: dozens of kinds of rice cake — steamed, fried, stuffed, soaked in syrup. Some villages hold whole pitha festivals." },
    khejurgur: { title: "Date-palm jaggery", native: "খেজুরের গুড়", note: "In winter, date palms are tapped at night; the sap is boiled down into dark, smoky gur by morning. It only exists a few months a year." },
    cha: { title: "Tong dokan cha", native: "চা", note: "Milky, sweet tea from a tiny roadside stall, in a small glass. Every village has one, and it's where all the news happens." },
    rivers: { title: "A land of rivers", native: "নদীমাতৃক দেশ", note: "Bangladesh has around seven hundred rivers. Boats are how millions of people get to school, to market and to each other." },
    kalboishakhi: { title: "Kalboishakhi", native: "কালবৈশাখী", note: "Sudden, wild storms in April and May: the sky goes dark in minutes, the wind bends the palms, and then — just as fast — the sun is back." },
    shapla: { title: "Shapla", native: "শাপলা", note: "The white water lily — Bangladesh's national flower. It opens in ponds all over the country." },
    ilish: { title: "Ilish", native: "ইলিশ", note: "The hilsa: silver, bony, and loved beyond reason. Fish from the Padma river is said to be the best. Everybody's Nana has an opinion on how to choose one." },
    fishmarket: { title: "The fish market", native: "মাছের বাজার", note: "Loud, wet and serious. Fish are lifted by the gills to check the colour; the bargaining is part of the ritual." },
    pohela: { title: "Pohela Boishakh", native: "পহেলা বৈশাখ", note: "April 14th — the first day of the Bengali year. Red and white clothes, music at dawn, fairs, and a breakfast of panta bhat and fried ilish." },
    shobhajatra: { title: "Mangal Shobhajatra", native: "মঙ্গল শোভাযাত্রা", note: "A huge New Year procession in Dhaka with giant painted masks of birds, tigers and fish — recognised by UNESCO as world heritage." },
    haalkhata: { title: "Haalkhata", native: "হালখাতা", note: "On New Year's Day, shops open a fresh red ledger and invite their customers in for sweets. Old debts are settled; new ones begin." },
    tuntuni: { title: "Tuntunir Boi", native: "টুনটুনির বই", note: "A book of folk tales collected by Upendrakishore Ray Chowdhury in 1910. Nearly every Bengali child knows the clever little tailorbird." },
    relatives: { title: "Mama, khala, chacha, fupu", native: "আত্মীয়", note: "Bengali has a different word for every aunt and uncle, depending on whether they're your mother's family or your father's." },
  },
  memoryNotes: {
    salam: { title: "Gave Nanu your salam", note: "And she gave you a blessing — and a biscuit." },
    dough: { title: "Helped Nanu with the dough", note: "চালের গুঁড়া, পানি, লবণ, গুড় — passed by ear." },
    pitha: { title: "Steamed bhapa pitha", note: "Flour, jaggery, coconut, cloth, steam." },
    haan: { title: "“হ্যাঁ, খাব!”", note: "Nanu offered another pitha. You said yes — in Bengali." },
    gear: { title: "Fetched Nana's fishing gear", note: "জাল, বড়শি, বালতি, ছাতা." },
    fish: { title: "Counted fish at the pond", note: "এক, দুই, তিন, চার." },
    opar: { title: "“ওপারে!”", note: "The boatman asked where you were going. The other side." },
    paid: { title: "Paid in taka", note: "দুই, তিন, পাঁচ, দশ — at the vegetable stall." },
    haggle: { title: "Watched Nana buy ilish", note: "Fourteen hundred became twelve hundred. The fish was worth it." },
    dhonnobad: { title: "“না, ধন্যবাদ!”", note: "The fish seller asked if you needed anything else." },
    alpona: { title: "Painted the alpona", note: "লাল, সাদা, হলুদ, সবুজ — on the courtyard floor." },
    sweets: { title: "Shared out the mishti", note: "Two, four, five, ten — from the haalkhata box." },
    shubho: { title: "“শুভ নববর্ষ!”", note: "Said back to the whole village on Pohela Boishakh." },
    test: { title: "Beat Rupa's word test", note: "Under the moon, among the fireflies." },
    story: { title: "Tuntuni and the cat", note: "Heard on a mat in the courtyard, by lantern light." },
    chalak: { title: "“খুব চালাক!”", note: "Nanu asked what Tuntuni was like. You knew." },
    keepsakes: { title: "Unpacked Bangladesh", note: "A clay mask, a red-and-white scarf, a jar of gur." },
    call: { title: "Named everyone on the call", note: "মামা, খালা, চাচা, ফুপু — which side is which." },
    retold: { title: "Told your trip in Bengali", note: "Boat, ilish, mela, Tuntuni — in order." },
    ashi: { title: "“আসি!”", note: "Not goodbye. I'll come again." },
  },
  chapters: [
    {
      n: 1,
      name: "Pitha",
      native: "পিঠা",
      subtitle: "Nanu arrives with winter",
      synopsis: "Nanu has flown in from Dhaka to Queens with a suitcase of rice flour and date-palm jaggery. Give her your salam, help with the dough, steam your first bhapa pitha — and say yes to another.",
      homeLines: {
        start: "Nanu's just arrived from Dhaka. She's at the front door.",
        going: "The dough's ready. Nanu's by the steaming pot.",
        done: "The pitha are gone and the tea is poured. Next: Nanu's village.",
      },
    },
    {
      n: 2,
      name: "The Village",
      native: "গ্রাম",
      subtitle: "River, pond and boat",
      synopsis: "April in Nanu's village by the river. Fetch Nana's fishing gear, count the fish in the pond, sit out a sudden storm — and tell the boatman where you're going.",
      homeLines: { start: "Nana's on the veranda with a fishing rod.", going: "The fish in the pond are still biting.", done: "Fish caught, river crossed. Next: the bazaar." },
    },
    {
      n: 3,
      name: "The Bazaar",
      native: "বাজার",
      subtitle: "Ilish and taka",
      synopsis: "The town bazaar with Nana: vegetables by ear, taka counted out, and the serious business of choosing an ilish — the national fish.",
      homeLines: { start: "Nana has the shopping bag and a look of determination.", going: "The ilish hasn't been chosen yet.", done: "The ilish is home. Next: Pohela Boishakh." },
    },
    {
      n: 4,
      name: "Pohela Boishakh",
      native: "পহেলা বৈশাখ",
      subtitle: "The Bengali New Year",
      synopsis: "April 14th: red and white everywhere. Paint the alpona, share out sweets from the haalkhata box, watch the procession of giant masks — and greet the new year back.",
      homeLines: { start: "The courtyard floor is waiting for its alpona.", going: "The procession is coming.", done: "শুভ নববর্ষ! Next: Nanu's story." },
    },
    {
      n: 5,
      name: "Tuntuni",
      native: "টুনটুনি",
      subtitle: "A story on the mat",
      synopsis: "A warm night in the village courtyard, a mat, a lantern and fireflies. Nanu tells the story of the tiny tailorbird who outwitted a very large cat.",
      homeLines: { start: "Nanu's spread the mat in the courtyard.", going: "Tuntuni is still hiding her chicks.", done: "Tuntuni's safe. Next: the family." },
    },
    {
      n: 6,
      name: "Family",
      native: "পরিবার",
      subtitle: "Calling Dhaka",
      synopsis: "Home in Queens. A video call to the whole family in Bangladesh: mama, khala, chacha, fupu — a different word for every side. Tell your trip in Bengali, and say goodbye the Bengali way: আসি.",
      homeLines: { start: "Dhaka is calling.", going: "Everyone's still on the call.", done: "আসি! You've finished the Bengali journey." },
    },
  ],
  highlight: { native: "শুভ নববর্ষ!", roman: "shubho noboborsho!", english: "Happy New Year!", context: "Said on Pohela Boishakh to everyone you meet — and they say it right back to you." },
};

export default meta;
