import type { Language } from "../types";

/* ARABIC · Levantine, as spoken at home · A Levantine family. One Arabic-speaking world among many: Egyptian, Gulf, Maghrebi and others would each be their own journey. */

const meta: Language = {
  id: "arabic",
  lang: "ar",
  speech: "ar",
  language: "Arabic",
  native: "العربية",
  family: "A Levantine family",
  variety: "Levantine Arabic, as spoken at home",
  script: "ar",
  dir: "rtl",
  romanize: true,
  line: "A Levantine family, from Sunday lunch at Teta's to the olive harvest in her village. Other Arabic-speaking regions will each be their own world.",
  journeys: ["Family and hospitality", "Food and celebration", "Stories and poetry", "Regional customs and everyday language"],
  a: "#3f7d55",
  b: "#c8704a",
  rank: 6,
  speakers: {
    teta: { name: "Teta", glyph: "ت", tone: "elder" },
    jiddo: { name: "Jiddo", glyph: "ج", tone: "elder" },
    khalto: { name: "Khalto", glyph: "خ", tone: "guest" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    { id: "mayy", native: "مي", roman: "mayy", english: "water", group: "food", where: "the jug in the kitchen", ch: 1 },
    { id: "khubz", native: "خبز", roman: "khubz", english: "bread", group: "food", where: "the bag in the kitchen", ch: 1 },
    { id: "zaytoon", native: "زيتون", roman: "zaytoon", english: "olives", group: "food", where: "a jar in the kitchen", ch: 1 },
    { id: "sukkar", native: "سكر", roman: "sukkar", english: "sugar", group: "food", where: "the tin in the kitchen", ch: 1 },
    { id: "laymoon", native: "ليمون", roman: "laymoon", english: "lemon", group: "food", where: "the balcony", ch: 1 },
    { id: "ahwe", native: "قهوة", roman: "ahwe", english: "coffee", group: "food", where: "Jiddo's coffee pot", ch: 1 },
    { id: "hummus", native: "حمص", roman: "hummus", english: "hummus", group: "food", where: "the table", ch: 1 },
    { id: "bayt", native: "بيت", roman: "bayt", english: "home · house", group: "home", where: "the photo of Teta's old house", ch: 1 },
    { id: "yasmeen", native: "ياسمين", roman: "yasmeen", english: "jasmine", group: "home", where: "the balcony", ch: 1 },
    { id: "ayle", native: "عيلة", roman: "‘ayle", english: "family", group: "family", where: "the photos in the salon", ch: 1 },
    { id: "mama", native: "ماما", roman: "mama", english: "mom", group: "family", where: "a photo in the salon", ch: 1 },
    { id: "baba", native: "بابا", roman: "baba", english: "dad", group: "family", where: "his chair on the balcony", ch: 1 },
    { id: "teta", native: "تيتا", roman: "teta", english: "grandma", group: "family", where: "the kitchen", ch: 1 },
    { id: "jiddo", native: "جدو", roman: "jiddo", english: "grandpa", group: "family", where: "the salon", ch: 1 },
    { id: "souq", native: "سوق", roman: "sū’", english: "market · souk", group: "home", where: "the old town", ch: 2 },
    { id: "kaak", native: "كعك", roman: "ka‘ak", english: "ka‘ak — sesame bread rings", group: "food", where: "Abu Samir's cart", ch: 2 },
    { id: "bandora", native: "بندورة", roman: "bandōra", english: "tomato", group: "food", where: "the vegetable stall", ch: 2 },
    { id: "khyar", native: "خيار", roman: "khyār", english: "cucumber", group: "food", where: "the vegetable stall", ch: 2 },
    { id: "mishmish", native: "مشمش", roman: "mishmish", english: "apricot", group: "food", where: "the vegetable stall", ch: 2 },
    { id: "tiin", native: "تين", roman: "tīn", english: "fig", group: "food", where: "the vegetable stall", ch: 2 },
    { id: "tnen", native: "تنين", roman: "tnēn", english: "two", group: "home", where: "counting ka‘ak", ch: 2 },
    { id: "tlete", native: "تلاتة", roman: "tlēte", english: "three", group: "home", where: "counting ka‘ak", ch: 2 },
    { id: "khamse", native: "خمسة", roman: "khamse", english: "five", group: "home", where: "counting ka‘ak", ch: 2 },
    { id: "ashra", native: "عشرة", roman: "‘ashra", english: "ten", group: "home", where: "counting ka‘ak", ch: 2 },
    { id: "addesh", native: "قديش؟", roman: "addēsh?", english: "how much?", group: "home", where: "Teta's bargaining", ch: 2 },
    { id: "ghali", native: "غالي", roman: "ghāli", english: "expensive", group: "home", where: "the za‘tar shop", ch: 2 },
    { id: "shukran", native: "شكراً", roman: "shukran", english: "thank you", group: "home", where: "the za‘tar shop", ch: 2 },
    { id: "eid", native: "عيد", roman: "‘īd", english: "feast · holiday", group: "home", where: "the week before the feast", ch: 3 },
    { id: "maamoul", native: "معمول", roman: "ma‘mūl", english: "ma‘mūl — filled feast cookies", group: "food", where: "Teta's trays", ch: 3 },
    { id: "khalto", native: "خالتو", roman: "khālto", english: "aunt (mom's sister)", group: "family", where: "the kitchen table", ch: 3 },
    { id: "ajine", native: "عجينة", roman: "‘ajīne", english: "dough", group: "food", where: "the big bowl", ch: 3 },
    { id: "smid", native: "سميد", roman: "smīd", english: "semolina", group: "food", where: "the sack by the door", ch: 3 },
    { id: "tamr", native: "تمر", roman: "tamr", english: "dates", group: "food", where: "the filling bowls", ch: 3 },
    { id: "joz", native: "جوز", roman: "jōz", english: "walnuts", group: "food", where: "the filling bowls", ch: 3 },
    { id: "fostoq", native: "فستق", roman: "fosto’", english: "pistachios", group: "food", where: "the filling bowls", ch: 3 },
    { id: "alab", native: "قالب", roman: "’ālab", english: "mould", group: "home", where: "Teta's wooden moulds", ch: 3 },
    { id: "seniyye", native: "صينية", roman: "ṣēniyye", english: "baking tray", group: "home", where: "the counter", ch: 3 },
    { id: "forn", native: "فرن", roman: "forn", english: "oven", group: "home", where: "the kitchen", ch: 3 },
    { id: "jiran", native: "جيران", roman: "jīrān", english: "neighbours", group: "family", where: "the stairwell", ch: 3 },
    { id: "bkhair", native: "وإنتو بخير", roman: "w intu bkhēr", english: "“and you too” — the reply to a feast greeting", group: "home", where: "the neighbours' door", ch: 3 },
    { id: "daya", native: "ضيعة", roman: "ḍay‘a", english: "village", group: "home", where: "Teta's village", ch: 4 },
    { id: "shajara", native: "شجرة", roman: "shajara", english: "tree", group: "home", where: "the olive grove", ch: 4 },
    { id: "shabake", native: "شبكة", roman: "shabake", english: "net", group: "home", where: "under the trees", ch: 4 },
    { id: "sillom", native: "سلّم", roman: "sillom", english: "ladder", group: "home", where: "the olive grove", ch: 4 },
    { id: "asa", native: "عصا", roman: "‘aṣa", english: "stick", group: "home", where: "the olive grove", ch: 4 },
    { id: "salle", native: "سلّة", roman: "salle", english: "basket", group: "home", where: "the olive grove", ch: 4 },
    { id: "maasara", native: "معصرة", roman: "ma‘ṣara", english: "olive press", group: "home", where: "the edge of the village", ch: 4 },
    { id: "zeit", native: "زيت", roman: "zēt", english: "oil", group: "food", where: "the olive press", ch: 4 },
    { id: "arbaa", native: "أربعة", roman: "arba‘a", english: "four", group: "home", where: "counting sacks", ch: 4 },
    { id: "sitte", native: "ستة", roman: "sitte", english: "six", group: "home", where: "counting sacks", ch: 4 },
    { id: "tmene", native: "تمانية", roman: "tmēne", english: "eight", group: "home", where: "counting sacks", ch: 4 },
    { id: "dabke", native: "دبكة", roman: "dabke", english: "dabke — the line dance", group: "home", where: "the square after the harvest", ch: 4 },
    { id: "yalla", native: "يلا", roman: "yalla", english: "come on · let's go", group: "home", where: "the square after the harvest", ch: 4 },
    { id: "hkeye", native: "حكاية", roman: "ḥkēye", english: "story · tale", group: "home", where: "Teta's cushions", ch: 5 },
    { id: "lel", native: "ليل", roman: "lēl", english: "night", group: "home", where: "the village at night", ch: 5 },
    { id: "amar", native: "قمر", roman: "’amar", english: "moon", group: "home", where: "over the village", ch: 5 },
    { id: "njum", native: "نجوم", roman: "njūm", english: "stars", group: "home", where: "over the village", ch: 5 },
    { id: "zghir", native: "زغير", roman: "zghīr", english: "small", group: "home", where: "Teta's story", ch: 5 },
    { id: "ghoule", native: "غولة", roman: "ghūle", english: "ghoula — an ogress from the stories", group: "home", where: "Teta's story", ch: 5 },
    { id: "nahr", native: "نهر", roman: "nahr", english: "river", group: "home", where: "Teta's story", ch: 5 },
    { id: "shater", native: "شاطر", roman: "shāṭer", english: "clever", group: "home", where: "Teta's story", ch: 5 },
    { id: "helwe", native: "حلوة", roman: "ḥelwe", english: "lovely · sweet", group: "home", where: "after the story", ch: 5 },
    { id: "shanta", native: "شنطة", roman: "shanṭa", english: "suitcase · bag", group: "home", where: "your room", ch: 6 },
    { id: "tizkar", native: "تذكار", roman: "tizkār", english: "keepsake", group: "home", where: "your suitcase", ch: 6 },
    { id: "ammo", native: "عمو", roman: "‘ammo", english: "uncle (dad's brother)", group: "family", where: "the video call", ch: 6 },
    { id: "ammto", native: "عمتو", roman: "‘ammto", english: "aunt (dad's sister)", group: "family", where: "the video call", ch: 6 },
    { id: "khalo", native: "خالو", roman: "khālo", english: "uncle (mom's brother)", group: "family", where: "the video call", ch: 6 },
    { id: "arib", native: "قريب", roman: "’arīb", english: "soon · near", group: "home", where: "saying goodbye", ch: 6 },
    { id: "ishtaet", native: "اشتقتلكن", roman: "ishta’tilkon", english: "I miss you (all)", group: "family", where: "saying goodbye", ch: 6 },
    { id: "maasalame", native: "مع السلامة", roman: "ma‘ as-salāme", english: "goodbye — “go with safety”", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    coffee: { title: "Arabic coffee", native: "قهوة", note: "Boiled with cardamom in a long-handled pot. Offering it is the first thing you do for a guest." },
    village: { title: "Teta's village", native: "الضيعة", note: "The house Teta grew up in, and olive trees Jiddo says are hundreds of years old." },
    zaatar: { title: "Za'atar", native: "زعتر", note: "Wild thyme, sumac and sesame. With olive oil on warm bread, it's breakfast." },
    oil: { title: "Olive oil from home", native: "زيت زيتون", note: "A tin from the village. Teta won't cook with any other." },
    naana: { title: "Fresh mint", native: "نعنع", note: "For the tea after lunch — and the tabbouleh, and the lemonade." },
    hospitality: { title: "Hospitality", native: "الضيافة", note: "The guest eats first and eats most. Saying no to a second plate is only the start of the conversation." },
    juha: { title: "Juha", native: "جحا", note: "The wise fool of Arabic folk tales, told for centuries across the Arab world — a cousin of Nasreddin Hodja in Turkish stories." },
    souq: { title: "The souk", native: "السوق", note: "Stone lanes with a roof of vines or tin, where the same families have sold the same things for generations." },
    kaak: { title: "Ka‘ak", native: "كعك", note: "Bread rings covered in sesame, sold from carts in the morning. You tear it open and sprinkle za‘tar inside." },
    refusal: { title: "The polite refusal", native: "لا، تسلم", note: "Offered something, you say no — at least once. The other person insists. It's a dance, and everybody knows the steps." },
    maamoul: { title: "Ma‘mūl", native: "معمول", note: "Semolina cookies pressed in carved wooden moulds. Muslim and Christian families across the Levant bake the same ones — for Eid, and for Easter." },
    moulds: { title: "Reading the shape", native: "القالب", note: "In Teta's kitchen: dates in the flat round ones, walnuts in the domes, pistachios in the long ovals. Other families swear by other shapes." },
    eidgreeting: { title: "“Kell ‘ām w intu bkhēr”", native: "كل عام وإنتو بخير", note: "“May every year find you well.” The greeting for every feast — and the answer is “w intu bkhēr”, and you too." },
    harvest: { title: "The olive harvest", native: "قطاف الزيتون", note: "Every autumn, whole families go back to the village. Nets under the trees, sticks, ladders, and lunch in the grove." },
    press: { title: "The olive press", native: "المعصرة", note: "The first oil comes out green and peppery. You dip bread straight into it, at the press." },
    dabke: { title: "Dabke", native: "دبكة", note: "A line dance, arms linked, feet stamping together. It's said the stamping began with neighbours packing down clay roofs as a team." },
    nussnsays: { title: "Nus Nsays", native: "نص نصيص", note: "“Half-Half” — the tiny, clever hero of Levantine folk tales, told to children for generations." },
    sahra: { title: "The sahra", native: "السهرة", note: "The long evening after dinner: tea, seeds, stories and nobody going to bed." },
  },
  memoryNotes: {
    kitchen: { title: "Helped Teta in the kitchen", note: "Bread, olives, water, sugar — found by ear, in Arabic." },
    table: { title: "Set the table for the guests", note: "Bread, olives, hummus and lemons. Nobody will leave hungry." },
    story: { title: "Juha and his donkey", note: "Pleasing everyone is a goal no one reaches." },
    welcome: { title: "“أهلا وسهلا!”", note: "You opened the door and welcomed the family in Arabic." },
    counted: { title: "Counted out ka‘ak", note: "Tnēn, tlēte, khamse, ‘ashra — for the whole family." },
    haggle: { title: "Watched Teta bargain", note: "The za‘tar was too expensive. Then, suddenly, it wasn't." },
    shukran: { title: "“بس هيك، شكراً!”", note: "The shopkeeper asked if you wanted anything else. You told him — in Arabic." },
    fillings: { title: "Helped Teta with the fillings", note: "Semolina, dates, walnuts, pistachios — by ear." },
    maamoul: { title: "Made ma‘mūl", note: "Knead, fill, press, tray, oven." },
    bkhair: { title: "“وإنتو بخير!”", note: "The neighbours wished you a happy feast. You answered them properly." },
    harvest: { title: "Brought in the olives", note: "Net, ladder, stick, basket." },
    sacks: { title: "Counted sacks at the press", note: "Arba‘a, sitte, tmēne — and the first green oil." },
    dabke: { title: "“أنا! يلا!”", note: "Jiddo asked who wanted to dance dabke. You joined the line." },
    nussnsays: { title: "Nus Nsays and the ghoula", note: "Heard on Teta's cushions, by lamplight." },
    helwe: { title: "“كتير حلوة!”", note: "You told Teta her story was lovely." },
    keepsakes: { title: "Unpacked the village", note: "A ma‘mūl mould, a bottle of new oil, a bag of za‘tar." },
    call: { title: "Named everyone on the call", note: "‘Ammo, ‘Ammto, Khālo, Khālto — whose side is whose." },
    retold: { title: "Told your trip in Arabic", note: "Ka‘ak, ma‘mūl, olives, Nus Nsays — in order." },
    salame: { title: "“مع السلامة!”", note: "Goodbye — go with safety. And come back soon." },
  },
  chapters: [
    {
      n: 1,
      name: "Ahlan wa Sahlan",
      native: "أهلا وسهلا",
      subtitle: "Sunday lunch at Teta's",
      synopsis:
        "Sunday lunch at Teta and Jiddo's, in Levantine Arabic. Pick lemons on the balcony, help Teta in the kitchen, set a table no guest could leave hungry — and when the doorbell rings, welcome the family the way Teta taught you.",
      homeLines: {
        start: "Sunday lunch at Teta's. The guests arrive in an hour.",
        going: "Teta's still cooking and the table's still bare.",
        done: "The family's all inside and lunch is served. Next: the souk.",
      },
    },
    {
      n: 2,
      name: "The Souk",
      native: "السوق",
      subtitle: "Za'atar by the kilo",
      synopsis: "A summer morning in Teta's town. Walk the souk with her, count out ka'ak for the family, and master the art of the polite refusal.",
      homeLines: { start: "Teta's at the door with her basket.", going: "The souk's busy, and Teta still has a list.", done: "Basket full, bargains won. Next: ma'amoul." },
    },
    {
      n: 3,
      name: "Ma'amoul",
      native: "المعمول",
      subtitle: "Cookies for the feast",
      synopsis: "Teta's kitchen before the feast. Press dough into carved wooden moulds — and learn why the shape tells you what's inside. Many Levantine families bake the same cookies for Eid and for Easter.",
      homeLines: { start: "Teta's got the wooden moulds out.", going: "The trays aren't full yet.", done: "Three trays of ma'amoul. Next: the village." },
    },
    {
      n: 4,
      name: "The Village",
      native: "الضيعة",
      subtitle: "Olive harvest",
      synopsis: "Autumn in Teta's village: nets under the trees, everyone up a ladder, and the first bottle of new oil. Then dabke, when the work is done.",
      homeLines: { start: "The nets are down. The olives are waiting.", going: "The nets are still filling up.", done: "The new oil's pressed. Next: stories." },
    },
    {
      n: 5,
      name: "Hikayat",
      native: "حكايات",
      subtitle: "Stories after dinner",
      synopsis: "After dinner in the village, Teta tells the story of Nus Nsays — Half-Half, the smallest boy in the village, and the cleverest.",
      homeLines: { start: "Teta's settled on the cushions. Time for a story.", going: "Nus Nsays is still in trouble.", done: "Half a boy, twice as clever. Next: the family." },
    },
    {
      n: 6,
      name: "The Family",
      native: "العيلة",
      subtitle: "Calling the village",
      synopsis: "Home again. A video call to the whole family in the village — uncles, aunts and cousins who talk faster than anyone you've ever met.",
      homeLines: { start: "The village is calling.", going: "Everyone's still on the call.", done: "The whole family, by name. You've finished the Arabic journey." },
    }
  ],
  highlight: { native: "أهلا وسهلا!", roman: "ahlan wa sahlan!", english: "Welcome!", context: "What you say when you open the door to your family. They answer in Arabic — and you understand." },
};

export default meta;
