import type { Language } from "../types";

/* PORTUGUESE · Brazilian, from Minas Gerais. Six chapters, from Vovó's pão de queijo to a call full of saudade. */

const meta: Language = {
  id: "portuguese",
  lang: "pt-BR",
  speech: "pt",
  language: "Portuguese",
  native: "Português",
  family: "A Brazilian family from Minas Gerais",
  variety: "Portuguese · Brazilian, from Minas Gerais",
  script: "latin",
  romanize: false,
  line: "A family from Minas Gerais, from Vovó's pão de queijo to a June festival in her hometown. One Portuguese-speaking world of many.",
  journeys: ["Food, coffee and the kitchen table", "Festas through the Brazilian year", "Folk tales and legends", "Other Portuguese-speaking families — Portugal, Angola, Mozambique, Cape Verde"],
  a: "#2f7d4a",
  b: "#d89a2a",
  rank: 8,
  cover: 4,
  speakers: {
    vovo: { name: "Vovó", glyph: "V", tone: "elder" },
    avo: { name: "Vovô", glyph: "V", tone: "elder" },
    mae: { name: "Mamãe", glyph: "M", tone: "parent" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    // ch1 — pão de queijo
    { id: "vovo", native: "Vovó", roman: "Vovó", english: "grandma", group: "family", where: "the front door", ch: 1 },
    { id: "mamae", native: "mamãe", roman: "mamãe", english: "mom", group: "family", where: "the kitchen", ch: 1 },
    { id: "papai", native: "papai", roman: "papai", english: "dad", group: "family", where: "the airport run", ch: 1 },
    { id: "familia", native: "família", roman: "família", english: "family", group: "family", where: "the photos in the hall", ch: 1 },
    { id: "casa", native: "casa", roman: "casa", english: "home · house", group: "home", where: "the front door", ch: 1 },
    { id: "oi", native: "oi", roman: "oi", english: "hi", group: "home", where: "the front door", ch: 1 },
    { id: "mala", native: "mala", roman: "mala", english: "suitcase", group: "home", where: "Vovó's luggage", ch: 1 },
    { id: "queijo", native: "queijo", roman: "queijo", english: "cheese", group: "food", where: "Vovó's suitcase", ch: 1 },
    { id: "polvilho", native: "polvilho", roman: "polvilho", english: "cassava starch", group: "food", where: "Vovó's suitcase", ch: 1 },
    { id: "ovos", native: "ovos", roman: "ovos", english: "eggs", group: "food", where: "the fridge", ch: 1 },
    { id: "leite", native: "leite", roman: "leite", english: "milk", group: "food", where: "the fridge", ch: 1 },
    { id: "oleo", native: "óleo", roman: "óleo", english: "oil", group: "food", where: "the cupboard", ch: 1 },
    { id: "forno", native: "forno", roman: "forno", english: "oven", group: "home", where: "the kitchen", ch: 1 },
    { id: "paodequeijo", native: "pão de queijo", roman: "pão de queijo", english: "cheese bread", group: "food", where: "Vovó's baking tray", ch: 1 },
    { id: "cafe", native: "café", roman: "café", english: "coffee", group: "food", where: "the coffee strainer", ch: 1 },
    { id: "quero", native: "quero", roman: "quero", english: "I want · yes please", group: "home", where: "the kitchen table", ch: 1 },
    // ch2 — a cidade
    { id: "avo", native: "Vovô", roman: "Vovô", english: "grandpa", group: "family", where: "the bench in the praça", ch: 2 },
    { id: "cidade", native: "cidade", roman: "cidade", english: "town · city", group: "home", where: "Vovó's hometown", ch: 2 },
    { id: "praca", native: "praça", roman: "praça", english: "town square", group: "home", where: "the middle of town", ch: 2 },
    { id: "igreja", native: "igreja", roman: "igreja", english: "church", group: "home", where: "the top of the hill", ch: 2 },
    { id: "padaria", native: "padaria", roman: "padaria", english: "bakery", group: "home", where: "the corner of the praça", ch: 2 },
    { id: "pao", native: "pão francês", roman: "pão francês", english: "bread roll", group: "food", where: "the padaria", ch: 2 },
    { id: "bolo", native: "bolo de fubá", roman: "bolo de fubá", english: "cornmeal cake", group: "food", where: "the padaria", ch: 2 },
    { id: "sonho", native: "sonho", roman: "sonho", english: "cream doughnut (lit. “dream”)", group: "food", where: "the padaria", ch: 2 },
    { id: "primo", native: "primo", roman: "primo", english: "cousin (boy)", group: "family", where: "the praça", ch: 2 },
    { id: "bola", native: "bola", roman: "bola", english: "ball", group: "home", where: "the pelada in the praça", ch: 2 },
    { id: "gol", native: "gol", roman: "gol", english: "goal", group: "home", where: "the pelada in the praça", ch: 2 },
    { id: "um", native: "um", roman: "um", english: "one", group: "home", where: "the pelada in the praça", ch: 2 },
    { id: "dois", native: "dois", roman: "dois", english: "two", group: "home", where: "the pelada in the praça", ch: 2 },
    { id: "tres", native: "três", roman: "três", english: "three", group: "home", where: "the pelada in the praça", ch: 2 },
    { id: "quatro", native: "quatro", roman: "quatro", english: "four", group: "home", where: "the pelada in the praça", ch: 2 },
    { id: "vamos", native: "vamos", roman: "vamos", english: "let's go · let's", group: "home", where: "the praça", ch: 2 },
    // ch3 — a feira
    { id: "feira", native: "feira", roman: "feira", english: "street market", group: "home", where: "Sunday in the town", ch: 3 },
    { id: "manga", native: "manga", roman: "manga", english: "mango", group: "food", where: "Seu Jorge's stall", ch: 3 },
    { id: "abacaxi", native: "abacaxi", roman: "abacaxi", english: "pineapple", group: "food", where: "Seu Jorge's stall", ch: 3 },
    { id: "banana", native: "banana", roman: "banana", english: "banana", group: "food", where: "Seu Jorge's stall", ch: 3 },
    { id: "maracuja", native: "maracujá", roman: "maracujá", english: "passion fruit", group: "food", where: "Seu Jorge's stall", ch: 3 },
    { id: "real", native: "real", roman: "real", english: "real (Brazil's money)", group: "home", where: "paying at the feira", ch: 3 },
    { id: "cinco", native: "cinco", roman: "cinco", english: "five", group: "home", where: "paying at the feira", ch: 3 },
    { id: "dez", native: "dez", roman: "dez", english: "ten", group: "home", where: "paying at the feira", ch: 3 },
    { id: "quanto", native: "quanto custa?", roman: "quanto custa?", english: "how much is it?", group: "home", where: "the flower stall", ch: 3 },
    { id: "caro", native: "caro", roman: "caro", english: "expensive", group: "home", where: "the flower stall", ch: 3 },
    { id: "pastel", native: "pastel", roman: "pastel", english: "pastel — a fried filled pastry", group: "food", where: "the pastel stand", ch: 3 },
    { id: "valeu", native: "valeu", roman: "valeu", english: "thanks! (casual)", group: "home", where: "the flower stall", ch: 3 },
    // ch4 — festa junina
    { id: "festajunina", native: "festa junina", roman: "festa junina", english: "June festival", group: "home", where: "the praça in June", ch: 4 },
    { id: "fogueira", native: "fogueira", roman: "fogueira", english: "bonfire", group: "home", where: "the middle of the festa", ch: 4 },
    { id: "bandeirinhas", native: "bandeirinhas", roman: "bandeirinhas", english: "little paper flags", group: "home", where: "strung over the praça", ch: 4 },
    { id: "milho", native: "milho", roman: "milho", english: "corn", group: "food", where: "the food stalls", ch: 4 },
    { id: "pamonha", native: "pamonha", roman: "pamonha", english: "pamonha — sweet corn paste in a husk", group: "food", where: "the food stalls", ch: 4 },
    { id: "pedemoleque", native: "pé de moleque", roman: "pé de moleque", english: "peanut brittle", group: "food", where: "the food stalls", ch: 4 },
    { id: "pipoca", native: "pipoca", roman: "pipoca", english: "popcorn", group: "food", where: "the food stalls", ch: 4 },
    { id: "chapeu", native: "chapéu de palha", roman: "chapéu de palha", english: "straw hat", group: "home", where: "everybody's head", ch: 4 },
    { id: "quadrilha", native: "quadrilha", roman: "quadrilha", english: "quadrilha — the June square dance", group: "home", where: "the dance floor", ch: 4 },
    { id: "chuva", native: "chuva", roman: "chuva", english: "rain", group: "home", where: "the quadrilha calls", ch: 4 },
    { id: "mentira", native: "mentira", roman: "mentira", english: "a lie · “not true!”", group: "home", where: "the quadrilha calls", ch: 4 },
    // ch5 — o saci
    { id: "sitio", native: "sítio", roman: "sítio", english: "small farm", group: "home", where: "Vovô's land outside town", ch: 5 },
    { id: "fogao", native: "fogão a lenha", roman: "fogão a lenha", english: "wood-burning stove", group: "home", where: "the farm kitchen", ch: 5 },
    { id: "vagalume", native: "vaga-lume", roman: "vaga-lume", english: "firefly", group: "home", where: "the farmyard at night", ch: 5 },
    { id: "historia", native: "história", roman: "história", english: "story", group: "home", where: "by the stove", ch: 5 },
    { id: "saci", native: "Saci", roman: "Saci", english: "the Saci — a one-legged trickster", group: "home", where: "Vovô's story", ch: 5 },
    { id: "gorro", native: "gorro vermelho", roman: "gorro vermelho", english: "red cap", group: "home", where: "Vovô's story", ch: 5 },
    { id: "perna", native: "perna", roman: "perna", english: "leg", group: "home", where: "Vovô's story", ch: 5 },
    { id: "redemoinho", native: "redemoinho", roman: "redemoinho", english: "dust whirlwind", group: "home", where: "Vovô's story", ch: 5 },
    { id: "peneira", native: "peneira", roman: "peneira", english: "sieve", group: "home", where: "Vovô's story", ch: 5 },
    { id: "foisaci", native: "foi o Saci!", roman: "foi o Saci!", english: "it was the Saci!", group: "home", where: "after the story", ch: 5 },
    // ch6 — a família
    { id: "lembranca", native: "lembrança", roman: "lembrança", english: "keepsake · memory", group: "home", where: "your suitcase", ch: 6 },
    { id: "tio", native: "tio", roman: "tio", english: "uncle", group: "family", where: "the video call", ch: 6 },
    { id: "tia", native: "tia", roman: "tia", english: "aunt", group: "family", where: "the video call", ch: 6 },
    { id: "prima", native: "prima", roman: "prima", english: "cousin (girl)", group: "family", where: "the video call", ch: 6 },
    { id: "logo", native: "logo", roman: "logo", english: "soon", group: "home", where: "saying goodbye", ch: 6 },
    { id: "saudade", native: "saudade", roman: "saudade", english: "saudade — missing someone, with love", group: "family", where: "saying goodbye", ch: 6 },
    { id: "beijo", native: "beijo", roman: "beijo", english: "kiss — how Brazilians sign off", group: "family", where: "saying goodbye", ch: 6 },
    { id: "atelogo", native: "até logo", roman: "até logo", english: "see you soon", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    abraco: { title: "Abraço e beijo", native: "abraço", note: "A big hug and a kiss on the cheek — one in Minas and Rio, two in São Paulo, three for luck if you're getting married." },
    cafe: { title: "Um cafezinho", native: "cafezinho", note: "Strong, sweet coffee in a tiny cup, poured through a cloth strainer. In Minas you're offered one within a minute of walking through any door." },
    paodequeijo: { title: "Pão de queijo", native: "pão de queijo", note: "Cheese bread from Minas Gerais, made with cassava starch instead of wheat — crisp outside, stretchy inside. Every family's recipe is the best one." },
    queijo: { title: "Queijo minas", native: "queijo minas", note: "The white farm cheese of Minas Gerais. Grandmothers have been known to carry it through international airports." },
    barroco: { title: "Baroque Minas", native: "barroco mineiro", note: "The old gold towns of Minas are full of 1700s churches covered in carved wood and gold leaf — built with the gold dug from the hills around them." },
    padaria: { title: "The padaria", native: "padaria", note: "The corner bakery: rolls in the morning, coffee all day, and a counter where the whole town catches up." },
    pelada: { title: "A pelada", native: "pelada", note: "A pick-up football game — in a praça, on a beach, in the street. Flip-flops for goalposts. Anyone can join." },
    feira: { title: "The feira", native: "feira livre", note: "Once a week, a street closes and fills with stalls. The sellers shout their prices — and their jokes — louder than each other." },
    pastel: { title: "Pastel e caldo de cana", native: "pastel", note: "A crisp fried pastry filled with cheese or meat, with a glass of fresh-pressed sugarcane juice. The official lunch of the feira." },
    pechinchar: { title: "Pechinchar", native: "pechinchar", note: "Bargaining. At the feira, a little pechincha is welcome — especially near closing time, when prices fall on their own." },
    festajunina: { title: "Festa junina", native: "festa junina", note: "June festivals for the saints — Santo Antônio, São João, São Pedro. Straw hats, checked shirts, bonfires and corn in every possible form." },
    quadrilha: { title: "The quadrilha", native: "quadrilha", note: "A square dance with a caller who shouts the moves. “Olha a chuva!” (Here comes the rain!) — and everyone shouts back “É mentira!” (It's a lie!)." },
    fogao: { title: "Fogão a lenha", native: "fogão a lenha", note: "The wood-burning stove of the Minas farmhouse. The coffee is always on it. So, usually, is a cat." },
    saci: { title: "The Saci-Pererê", native: "Saci-Pererê", note: "Brazil's favourite trickster: a one-legged boy with a red cap and a pipe who braids horses' manes and hides your things. Brazil celebrates him on October 31st." },
  },
  memoryNotes: {
    abraco: { title: "Hugged Vovó", note: "A big abraço and one beijo on the cheek." },
    batter: { title: "Helped with the dough", note: "Polvilho, ovos, leite, óleo — passed by ear." },
    baked: { title: "Baked pão de queijo", note: "Mix, add cheese, roll, oven." },
    quero: { title: "“Quero, sim!”", note: "Vovó offered another pão de queijo. You said yes — in Portuguese." },
    bread: { title: "Bought bread at the padaria", note: "Pão francês, sonho, bolo de fubá." },
    pelada: { title: "Played the pelada", note: "Um, dois, três, quatro gols." },
    vamos: { title: "“Vamos!”", note: "Your primo asked if you'd play again tomorrow." },
    paid: { title: "Paid in reais", note: "Dois, três, cinco, dez — at Seu Jorge's stall." },
    haggle: { title: "Watched Vovó pechinchar", note: "Twenty reais became fifteen, and a free flower." },
    valeu: { title: "“É só isso, valeu!”", note: "The flower seller asked if you wanted anything else." },
    stalls: { title: "Filled a plate at the festa", note: "Milho, pamonha, pé de moleque, pipoca." },
    dance: { title: "Danced the quadrilha", note: "Balancê, túnel, caminho da roça." },
    mentira: { title: "“É mentira!”", note: "The caller shouted “Olha a chuva!” You knew the answer." },
    test: { title: "Beat Bia's word test", note: "Under a sky full of fireflies." },
    story: { title: "The Saci-Pererê", note: "Heard by the wood stove at Vovô's sítio." },
    foisaci: { title: "“Foi o Saci!”", note: "Somebody tied your shoelaces together. You know who." },
    keepsakes: { title: "Unpacked Minas", note: "A straw hat, a block of queijo minas, a very small red cap." },
    call: { title: "Named everyone on the call", note: "Tio, tia, primo, prima." },
    retold: { title: "Told your trip in Portuguese", note: "Padaria, feira, fogueira, Saci — in order." },
    atelogo: { title: "“Até logo!”", note: "Not goodbye. See you soon. Beijo." },
  },
  chapters: [
    {
      n: 1,
      name: "Pão de Queijo",
      native: "Pão de Queijo",
      subtitle: "Vovó arrives from Minas",
      synopsis: "Vovó has flown in from Minas Gerais with a whole cheese in her suitcase. Greet her with an abraço, help her with the dough, bake your first pão de queijo — and learn how to say yes to another one.",
      homeLines: {
        start: "Vovó's just arrived from Minas. She's at the front door, arms open.",
        going: "The dough's ready. Vovó's waiting by the oven.",
        done: "The pão de queijo is gone and the coffee is on. Next: Vovó's hometown.",
      },
    },
    {
      n: 2,
      name: "A Cidade",
      native: "A Cidade",
      subtitle: "The praça and the padaria",
      synopsis: "June in Vovó's little gold-rush town: cobbled hills, a baroque church, and a praça where everyone knows everyone. Buy bread at the padaria and join your primo's football game.",
      homeLines: { start: "Vovô wants bread from the padaria.", going: "The pelada in the praça is still going.", done: "Bread home, goals scored. Next: the Sunday feira." },
    },
    {
      n: 3,
      name: "A Feira",
      native: "A Feira",
      subtitle: "Sunday market, loud and sweet",
      synopsis: "The Sunday street market: mangoes, pineapples, passion fruit and sellers who shout jokes. Fill Vovó's bag by ear, count out reais, eat a pastel — and watch Vovó bargain for flowers.",
      homeLines: { start: "Vovó's shopping trolley is by the door.", going: "The feira's loud and Vovó still has a list.", done: "Bag full, flowers bought. Next: the festa junina." },
    },
    {
      n: 4,
      name: "Festa Junina",
      native: "Festa Junina",
      subtitle: "Straw hats and bonfires",
      synopsis: "June, and the whole town is in straw hats and checked shirts. Fill a plate at the corn stalls, dance the quadrilha — and don't be fooled when the caller says it's raining.",
      homeLines: { start: "The bandeirinhas are up and the bonfire's lit.", going: "The quadrilha is about to start.", done: "Danced, fed and not fooled. Next: Vovô's story." },
    },
    {
      n: 5,
      name: "O Saci",
      native: "O Saci",
      subtitle: "A story by the wood stove",
      synopsis: "A night at Vovô's farm outside town. Fireflies in the dark, coffee on the wood stove, and Vovô's story about the one-legged trickster with the red cap.",
      homeLines: { start: "Vovô's lit the wood stove.", going: "The Saci's still up to something.", done: "Your shoelaces are tied together. You know who did it. Next: the family." },
    },
    {
      n: 6,
      name: "A Família",
      native: "A Família",
      subtitle: "Calling Minas",
      synopsis: "Home again, and full of saudade. A video call to Minas: tios, tias, primos. Put names to everyone, tell your whole trip in Portuguese — and sign off the Brazilian way.",
      homeLines: { start: "Minas is calling.", going: "Everyone's still on the call.", done: "Até logo, Minas. You've finished the Portuguese journey." },
    },
  ],
  highlight: { native: "É mentira!", roman: "", english: "It's a lie!", context: "What the whole festa shouts back when the quadrilha caller cries “Olha a chuva!” — and now you shout it too." },
};

export default meta;
