import type { Language } from "../types";

/* CHINESE · Mandarin, simplified characters · A Chinese-American family with roots in Shandong. */

const meta: Language = {
  id: "chinese",
  lang: "zh-Hans",
  speech: "zh",
  language: "Chinese",
  native: "中文",
  family: "A Chinese-American family",
  variety: "Mandarin · simplified characters",
  script: "zh",
  romanize: true,
  line: "A Chinese-American family, from New Year's Eve to Nǎinai's hometown in Shandong. Built for regional worlds, not one flattened picture.",
  journeys: ["Family and the table", "Festivals and the lunar year", "Regional stories and dialects", "Everyday life across generations"],
  a: "#b8452f",
  b: "#d9a441",
  rank: 2,
  speakers: {
    nainai: { name: "Nǎinai", glyph: "奶", tone: "elder" },
    mama: { name: "Māma", glyph: "妈", tone: "parent" },
    yeye: { name: "Yéye", glyph: "爷", tone: "elder" },
    guide: { name: "Your journal", glyph: "✦", tone: "guide" },
    you: { name: "{name}", glyph: "", tone: "you" },
  },
  words: [
    { id: "shui", native: "水", roman: "shuǐ", english: "water", group: "food", where: "the kettle in the kitchen", ch: 1 },
    { id: "jiaozi", native: "饺子", roman: "jiǎozi", english: "dumplings", group: "food", where: "Nǎinai's board", ch: 1 },
    { id: "mianfen", native: "面粉", roman: "miànfěn", english: "flour", group: "food", where: "the kitchen counter", ch: 1 },
    { id: "baicai", native: "白菜", roman: "báicài", english: "napa cabbage", group: "food", where: "the kitchen counter", ch: 1 },
    { id: "kuaizi", native: "筷子", roman: "kuàizi", english: "chopsticks", group: "home", where: "the sideboard", ch: 1 },
    { id: "wan", native: "碗", roman: "wǎn", english: "bowl", group: "home", where: "the sideboard", ch: 1 },
    { id: "fu", native: "福", roman: "fú", english: "good fortune", group: "home", where: "the front door", ch: 1 },
    { id: "denglong", native: "灯笼", roman: "dēnglong", english: "lantern", group: "home", where: "the front hall", ch: 1 },
    { id: "hongbao", native: "红包", roman: "hóngbāo", english: "red envelope", group: "home", where: "Nǎinai's sleeve", ch: 1 },
    { id: "jia", native: "家", roman: "jiā", english: "home · family", group: "family", where: "the photo in the hall", ch: 1 },
    { id: "mama", native: "妈妈", roman: "māma", english: "mom", group: "family", where: "the dinner table", ch: 1 },
    { id: "baba", native: "爸爸", roman: "bàba", english: "dad", group: "family", where: "the dinner table", ch: 1 },
    { id: "nainai", native: "奶奶", roman: "nǎinai", english: "grandma (dad's mother)", group: "family", where: "the dining room", ch: 1 },
    { id: "yeye", native: "爷爷", roman: "yéye", english: "grandpa (dad's father)", group: "family", where: "the dinner table", ch: 1 },
    { id: "zaoshi", native: "早市", roman: "zǎoshì", english: "morning market", group: "home", where: "the lane behind Nǎinai's building", ch: 2 },
    { id: "dacong", native: "大葱", roman: "dàcōng", english: "Shandong scallions", group: "food", where: "the vegetable cart", ch: 2 },
    { id: "baozi", native: "包子", roman: "bāozi", english: "steamed buns", group: "food", where: "Wáng Āyí's steamer", ch: 2 },
    { id: "jidan", native: "鸡蛋", roman: "jīdàn", english: "egg", group: "food", where: "the vegetable cart", ch: 2 },
    { id: "pingguo", native: "苹果", roman: "píngguǒ", english: "apple", group: "food", where: "Lǎo Lǐ's apple cart", ch: 2 },
    { id: "doujiang", native: "豆浆", roman: "dòujiāng", english: "soy milk", group: "food", where: "Wáng Āyí's stall", ch: 2 },
    { id: "kuai", native: "块", roman: "kuài", english: "yuan (money, spoken)", group: "home", where: "paying at the market", ch: 2 },
    { id: "liang", native: "两", roman: "liǎng", english: "two (of something)", group: "home", where: "paying at the market", ch: 2 },
    { id: "san", native: "三", roman: "sān", english: "three", group: "home", where: "paying at the market", ch: 2 },
    { id: "wu", native: "五", roman: "wǔ", english: "five", group: "home", where: "paying at the market", ch: 2 },
    { id: "shi", native: "十", roman: "shí", english: "ten", group: "home", where: "paying at the market", ch: 2 },
    { id: "duoshaoqian", native: "多少钱？", roman: "duōshao qián?", english: "how much?", group: "home", where: "Nǎinai's bargaining", ch: 2 },
    { id: "taigui", native: "太贵了", roman: "tài guì le", english: "too expensive", group: "home", where: "Lǎo Lǐ's apple cart", ch: 2 },
    { id: "xiexie", native: "谢谢", roman: "xièxie", english: "thank you", group: "home", where: "Lǎo Lǐ's apple cart", ch: 2 },
    { id: "shengri", native: "生日", roman: "shēngrì", english: "birthday", group: "home", where: "Nǎinai's birthday", ch: 3 },
    { id: "shushu", native: "叔叔", roman: "shūshu", english: "uncle (dad's younger brother)", group: "family", where: "the kitchen door", ch: 3 },
    { id: "tangmei", native: "堂妹", roman: "tángmèi", english: "younger cousin (girl, dad's side)", group: "family", where: "the courtyard", ch: 3 },
    { id: "mian", native: "面条", roman: "miàntiáo", english: "noodles", group: "food", where: "Yéye's board", ch: 3 },
    { id: "miantuan", native: "面团", roman: "miàntuán", english: "dough", group: "food", where: "Yéye's board", ch: 3 },
    { id: "la", native: "拉", roman: "lā", english: "pull", group: "food", where: "Yéye's hands", ch: 3 },
    { id: "chang", native: "长", roman: "cháng", english: "long", group: "home", where: "the noodle", ch: 3 },
    { id: "guo", native: "锅", roman: "guō", english: "pot · wok", group: "home", where: "the stove", ch: 3 },
    { id: "tang", native: "汤", roman: "tāng", english: "soup", group: "food", where: "the stove", ch: 3 },
    { id: "changshoumian", native: "长寿面", roman: "chángshòu miàn", english: "longevity noodles", group: "food", where: "Nǎinai's bowl", ch: 3 },
    { id: "shengrikuaile", native: "生日快乐", roman: "shēngrì kuàilè", english: "happy birthday", group: "home", where: "Nǎinai's birthday", ch: 3 },
    { id: "zhongqiu", native: "中秋", roman: "zhōngqiū", english: "Mid-Autumn", group: "home", where: "the courtyard", ch: 4 },
    { id: "yuebing", native: "月饼", roman: "yuèbing", english: "mooncake", group: "food", where: "the gift boxes", ch: 4 },
    { id: "yueliang", native: "月亮", roman: "yuèliang", english: "the moon", group: "home", where: "over the courtyard", ch: 4 },
    { id: "yuan", native: "圆", roman: "yuán", english: "round · full", group: "home", where: "the moon", ch: 4 },
    { id: "cha", native: "茶", roman: "chá", english: "tea", group: "food", where: "the courtyard table", ch: 4 },
    { id: "dengmi", native: "灯谜", roman: "dēngmí", english: "lantern riddle", group: "home", where: "under the lanterns", ch: 4 },
    { id: "cai", native: "猜", roman: "cāi", english: "guess", group: "home", where: "under the lanterns", ch: 4 },
    { id: "si", native: "四", roman: "sì", english: "four", group: "home", where: "the gift boxes", ch: 4 },
    { id: "liu", native: "六", roman: "liù", english: "six", group: "home", where: "the gift boxes", ch: 4 },
    { id: "ba", native: "八", roman: "bā", english: "eight", group: "home", where: "the gift boxes", ch: 4 },
    { id: "tuanyuan", native: "团圆", roman: "tuányuán", english: "reunion · together again", group: "family", where: "the courtyard table", ch: 4 },
    { id: "gushi", native: "故事", roman: "gùshi", english: "story", group: "home", where: "on the roof", ch: 5 },
    { id: "taiyang", native: "太阳", roman: "tàiyáng", english: "sun", group: "home", where: "Nǎinai's story", ch: 5 },
    { id: "yao", native: "药", roman: "yào", english: "medicine · elixir", group: "home", where: "Nǎinai's story", ch: 5 },
    { id: "fei", native: "飞", roman: "fēi", english: "fly", group: "home", where: "Nǎinai's story", ch: 5 },
    { id: "change", native: "嫦娥", roman: "Cháng'é", english: "Chang'e, the moon lady", group: "home", where: "Nǎinai's story", ch: 5 },
    { id: "yutu", native: "玉兔", roman: "yùtù", english: "the jade rabbit", group: "home", where: "Nǎinai's story", ch: 5 },
    { id: "xingxing", native: "星星", roman: "xīngxing", english: "stars", group: "home", where: "on the roof", ch: 5 },
    { id: "tian", native: "天", roman: "tiān", english: "sky · day", group: "home", where: "on the roof", ch: 5 },
    { id: "wuding", native: "屋顶", roman: "wūdǐng", english: "roof", group: "home", where: "the stairs up", ch: 5 },
    { id: "xiangzi", native: "箱子", roman: "xiāngzi", english: "suitcase · box", group: "home", where: "your room", ch: 6 },
    { id: "jinian", native: "纪念", roman: "jìniàn", english: "keepsake", group: "home", where: "your suitcase", ch: 6 },
    { id: "shenshen", native: "婶婶", roman: "shěnshen", english: "aunt (Shūshu's wife)", group: "family", where: "the video call", ch: 6 },
    { id: "tangge", native: "堂哥", roman: "tánggē", english: "older cousin (boy, dad's side)", group: "family", where: "the video call", ch: 6 },
    { id: "xiangni", native: "想你", roman: "xiǎng nǐ", english: "miss you", group: "family", where: "the video call", ch: 6 },
    { id: "mingnian", native: "明年", roman: "míngnián", english: "next year", group: "home", where: "saying goodbye", ch: 6 },
    { id: "zaijian", native: "再见", roman: "zàijiàn", english: "goodbye — “see you again”", group: "home", where: "saying goodbye", ch: 6 },
  ],
  cultureNotes: {
    fu: { title: "The upside-down 福", native: "福到了", note: "倒 (dào, upside down) sounds exactly like 到 (dào, arrive) — so an upside-down fú says good fortune has arrived." },
    couplets: { title: "Spring couplets", native: "春联", note: "Two matching lines of poetry pasted either side of the door, with a four-character blessing across the top." },
    bamboo: { title: "Lucky bamboo", native: "富贵竹", note: "Given in threes, fives and eights. Never four — 四 (sì) sounds like 死 (sǐ)." },
    plum: { title: "Plum blossom", native: "梅花", note: "The flower that blooms in the cold. A picture of patience." },
    fish: { title: "Fish for plenty", native: "年年有余", note: "鱼 (yú, fish) sounds like 余 (yú, surplus). A whole fish on the table means plenty every year." },
    jiaozi: { title: "Dumplings", native: "饺子", note: "Folded to look like old silver ingots. Many families, especially in the north, make them together on New Year's Eve." },
    seating: { title: "The seat of honour", native: "上座", note: "Facing the door, for the eldest — even at a round table." },
    nian: { title: "The story of Nián", native: "年", note: "The monster scared off by red and noise. 过年 — celebrating New Year — literally means “getting past Nián”." },
    steamer: { title: "Bamboo steamers", native: "蒸笼", note: "Stacked three high over one pot of boiling water." },
    zaoshi: { title: "The morning market", native: "早市", note: "Set up before dawn, packed away by nine. Retired neighbours come for the vegetables and stay for the gossip." },
    dacong: { title: "Shandong scallions", native: "章丘大葱", note: "Shandong grows scallions taller than a child. Eaten raw, rolled in a jiānbing, by people who swear it's not strong at all." },
    jianbing: { title: "Jiānbing", native: "煎饼", note: "A crepe cooked on a hot iron disc, egg cracked on top, folded around a crispy cracker. Shandong's breakfast." },
    apples: { title: "Yantai apples", native: "烟台苹果", note: "The Shandong coast has grown apples since the 1870s. Everyone in Yantai will tell you theirs are the best in China." },
    changshou: { title: "Longevity noodles", native: "长寿面", note: "One long noodle for a long life. Birthday noodles are never cut — and you try not to bite through them." },
    peach: { title: "Longevity peaches", native: "寿桃", note: "Steamed buns shaped like peaches, pink at the tip. A birthday wish for a long life." },
    zhongqiu: { title: "Mid-Autumn Festival", native: "中秋节", note: "The fifteenth day of the eighth lunar month, when the moon is fullest. Families gather — the round moon means everyone together." },
    yuebing: { title: "Mooncakes", native: "月饼", note: "Lotus paste, red bean, five nuts — some with a salted egg yolk inside, like a little moon. Given in boxes to everyone you know." },
    dengmi: { title: "Lantern riddles", native: "灯谜", note: "Riddles written on paper hung under the lanterns. Guess right and you win a sweet — or at least the right to be smug." },
    change: { title: "Chang'e", native: "嫦娥", note: "The lady in the moon. China's lunar probes are named after her — and its moon rover after the jade rabbit." },
    roof: { title: "Moon-watching", native: "赏月", note: "Sitting out on a roof or a balcony with tea and mooncakes, just looking at the moon. That's the whole plan. That's the festival." },
  },
  memoryNotes: {
    dumplings: { title: "Made dumplings with Nǎinai", note: "Flour, water, cabbage, a bowl — fetched in Mandarin." },
    table: { title: "Seated the family", note: "Yéye facing the door, everyone in their place." },
    story: { title: "The story of Nián", note: "Why everything tonight is red." },
    newyear: { title: "“新年快乐！”", note: "Nǎinai gave you a hóngbāo. You thanked her the right way." },
    paid: { title: "Paid in yuan", note: "Liǎng, sān, wǔ, shí kuài — counted out at the market." },
    haggle: { title: "Watched Nǎinai bargain", note: "Twelve yuan became ten, and a free apple." },
    xiexie: { title: "“不要了，谢谢！”", note: "Lǎo Lǐ asked if you wanted anything else. You told him — in Mandarin." },
    kitchen: { title: "Helped Yéye in the kitchen", note: "Flour, water, eggs, the pot — by ear." },
    noodles: { title: "Pulled longevity noodles", note: "Mix, knead, pull, into the pot, add the soup." },
    birthday: { title: "“奶奶，生日快乐！”", note: "You wished Nǎinai a happy birthday in Mandarin." },
    boxes: { title: "Packed the mooncake boxes", note: "Four, six, eight — never the wrong number." },
    riddle: { title: "Guessed the lantern riddle", note: "What gets dirtier the more you wash it? Water." },
    tuanyuan: { title: "Mid-Autumn together", note: "Round moon, round table, everyone there." },
    moonstory: { title: "Chang'e and the jade rabbit", note: "Heard on the roof, under the Mid-Autumn moon." },
    moon: { title: "“嫦娥和玉兔！”", note: "Nǎinai asked who lives on the moon. You knew." },
    keepsakes: { title: "Unpacked Shandong", note: "A mooncake tin, a paper lantern, a very long chopstick." },
    call: { title: "Named everyone on the call", note: "Shūshu, Shěnshen, Tánggē, Tángmèi." },
    retold: { title: "Told your summer in Mandarin", note: "Bāozi, noodles, mooncakes, Chang'e — in order." },
    zaijian: { title: "“明年见！”", note: "Not goodbye. See you next year." },
  },
  chapters: [
    {
      n: 1,
      name: "Reunion Dinner",
      native: "团圆饭",
      subtitle: "New Year's Eve at home",
      synopsis:
        "Lunar New Year's Eve in a Chinese-American home. Put the 福 on the door (upside down, on purpose), wrap dumplings with Nǎinai, seat the family around the round table — and find out why everything tonight is red.",
      homeLines: {
        start: "It's New Year's Eve, and the 福 still isn't on the door.",
        going: "Nǎinai is at the dining table. Reunion dinner won't make itself.",
        done: "Reunion dinner is done and your hóngbāo is safe. Next: the morning market.",
      },
    },
    {
      n: 2,
      name: "The Morning Market",
      native: "早市",
      subtitle: "Numbers before breakfast",
      synopsis: "Summer in Nǎinai's hometown in Shandong. Walk to the morning market with her, buy scallions and buns, count out yuan, and learn which stall she trusts.",
      homeLines: { start: "Nǎinai's at the door with her shopping bag.", going: "The morning market closes at nine. Nǎinai's list isn't done.", done: "Breakfast is bought. Next: noodles by hand." },
    },
    {
      n: 3,
      name: "Noodles by Hand",
      native: "拉面",
      subtitle: "Long life, one pull at a time",
      synopsis: "It's Nǎinai's birthday, and Yéye is making longevity noodles by hand. Learn the steps, help him pull — and find out why birthday noodles are never cut.",
      homeLines: { start: "Yéye's rolling up his sleeves. It's Nǎinai's birthday.", going: "The dough is resting. Yéye's waiting for you.", done: "One very long noodle, uncut. Next: Mid-Autumn." },
    },
    {
      n: 4,
      name: "Mid-Autumn",
      native: "中秋",
      subtitle: "Mooncakes and lanterns",
      synopsis: "The full moon, a table of mooncakes, and lanterns with riddles hanging from them. Solve a riddle, share one mooncake between everyone, and look for the rabbit.",
      homeLines: { start: "The moon's coming up. Nǎinai has the mooncakes.", going: "There are still riddles on the lanterns.", done: "The moon's full and so is everyone. Next: the story of Chang'e." },
    },
    {
      n: 5,
      name: "Stories",
      native: "故事",
      subtitle: "Chang'e and the moon",
      synopsis: "On the roof under the Mid-Autumn moon, Nǎinai tells the story of Chang'e, who flew to the moon, and the jade rabbit who keeps her company.",
      homeLines: { start: "Nǎinai's on the roof, looking at the moon.", going: "Nǎinai hasn't finished the story.", done: "Chang'e and the rabbit, kept. Next: home." },
    },
    {
      n: 6,
      name: "Home",
      native: "家",
      subtitle: "Calling across the ocean",
      synopsis: "Back home, a video call to the cousins in Shandong. Their dialect sounds different; the teasing is exactly the same. Use everything you've learned.",
      homeLines: { start: "The cousins are calling from Shandong.", going: "Everyone's still on the call.", done: "Home, both of them. You've finished the Chinese journey." },
    }
  ],
  highlight: { native: "新年快乐！", roman: "xīnnián kuàilè!", english: "Happy New Year!", context: "What you say when Nǎinai hands you a red envelope — before you've even thought about it." },
};

export default meta;
